CREATE TABLE Lugar (
	"id" SERIAL,
	"tipo" varchar(200) NOT NULL,
	"nombre" varchar(200) NOT NULL,
	"fk_lugar" integer
);

INSERT INTO Lugar (tipo, nombre) VALUES
('Estado','Amazonas'),
('Estado','Anzoátegui'),
('Estado','Apure'),
('Estado','Aragua'),
('Estado','Barinas'),
('Estado','Bolívar'),
('Estado','Carabobo'),
('Estado','Cojedes'),
('Estado','Delta Amacuro'),
('Estado', 'Falcón'),
('Estado', 'Guárico'),
('Estado', 'Lara'),
('Estado', 'Mérida'),
('Estado', 'Miranda'),
('Estado', 'Monagas'),
('Estado', 'Nueva Esparta'),
('Estado', 'Portuguesa'),
('Estado', 'Sucre'),
('Estado', 'Táchira'),
('Estado', 'Trujillo'),
('Estado', 'Vargas'),
('Estado', 'Yaracuy'),
('Estado', 'Zulia'),
('Estado', 'Distrito Capital'),
('Estado', 'Dependencias Federales');

/* MUNICIPOS */
INSERT INTO Lugar (fk_lugar, tipo, nombre) VALUES
(1, 'Municipio', 'Alto Orinoco'),
(1, 'Municipio', 'Atabapo'),
(1, 'Municipio', 'Atures'),
(1, 'Municipio', 'Autana'),
(1, 'Municipio', 'Manapiare'),
(1, 'Municipio', 'Maroa'),
(1, 'Municipio', 'Río Negro'),
(2, 'Municipio', 'Anaco'),
(2, 'Municipio', 'Aragua'),
(2, 'Municipio', 'Manuel Ezequiel Bruzual'),
(2, 'Municipio', 'Diego Bautista Urbaneja'),
(2, 'Municipio', 'Fernando Peñalver'),
(2, 'Municipio', 'Francisco Del Carmen Carvajal'),
(2, 'Municipio', 'General Sir Arthur McGregor'),
(2, 'Municipio', 'Guanta'),
(2, 'Municipio', 'Independencia'),
(2, 'Municipio', 'José Gregorio Monagas'),
(2, 'Municipio', 'Juan Antonio Sotillo'),
(2, 'Municipio', 'Juan Manuel Cajigal'),
(2, 'Municipio', 'Libertad'),
(2, 'Municipio', 'Francisco de Miranda'),
(2, 'Municipio', 'Pedro María Freites'),
(2, 'Municipio', 'Píritu'),
(2, 'Municipio', 'San José de Guanipa'),
(2, 'Municipio', 'San Juan de Capistrano'),
(2, 'Municipio', 'Santa Ana'),
(2, 'Municipio', 'Simón Bolívar'),
(2, 'Municipio', 'Simón Rodríguez'),
(3, 'Municipio', 'Achaguas'),
(3, 'Municipio', 'Biruaca'),
(3, 'Municipio', 'Muñóz'),
(3, 'Municipio', 'Páez'),
(3, 'Municipio', 'Pedro Camejo'),
(3, 'Municipio', 'Rómulo Gallegos'),
(3, 'Municipio', 'San Fernando'),
(4, 'Municipio', 'Atanasio Girardot'),
(4, 'Municipio', 'Bolívar'),
(4, 'Municipio', 'Camatagua'),
(4, 'Municipio', 'Francisco Linares Alcántara'),
(4, 'Municipio', 'José Ángel Lamas'),
(4, 'Municipio', 'José Félix Ribas'),
(4, 'Municipio', 'José Rafael Revenga'),
(4, 'Municipio', 'Libertador'),
(4, 'Municipio', 'Mario Briceño Iragorry'),
(4, 'Municipio', 'Ocumare de la Costa de Oro'),
(4, 'Municipio', 'San Casimiro'),
(4, 'Municipio', 'San Sebastián'),
(4, 'Municipio', 'Santiago Mariño'),
(4, 'Municipio', 'Santos Michelena'),
(4, 'Municipio', 'Sucre'),
(4, 'Municipio', 'Tovar'),
(4, 'Municipio', 'Urdaneta'),
(4, 'Municipio', 'Zamora'),
(5, 'Municipio', 'Alberto Arvelo Torrealba'),
(5, 'Municipio', 'Andrés Eloy Blanco'),
(5, 'Municipio', 'Antonio José de Sucre'),
(5, 'Municipio', 'Arismendi'),
(5, 'Municipio', 'Barinas'),
(5, 'Municipio', 'Bolívar'),
(5, 'Municipio', 'Cruz Paredes'),
(5, 'Municipio', 'Ezequiel Zamora'),
(5, 'Municipio', 'Obispos'),
(5, 'Municipio', 'Pedraza'),
(5, 'Municipio', 'Rojas'),
(5, 'Municipio', 'Sosa'),
(6, 'Municipio', 'Caroní'),
(6, 'Municipio', 'Cedeño'),
(6, 'Municipio', 'El Callao'),
(6, 'Municipio', 'Gran Sabana'),
(6, 'Municipio', 'Heres'),
(6, 'Municipio', 'Piar'),
(6, 'Municipio', 'Angostura (Raúl Leoni)'),
(6, 'Municipio', 'Roscio'),
(6, 'Municipio', 'Sifontes'),
(6, 'Municipio', 'Sucre'),
(6, 'Municipio', 'Padre Pedro Chien'),
(7, 'Municipio', 'Bejuma'),
(7, 'Municipio', 'Carlos Arvelo'),
(7, 'Municipio', 'Diego Ibarra'),
(7, 'Municipio', 'Guacara'),
(7, 'Municipio', 'Juan José Mora'),
(7, 'Municipio', 'Libertador'),
(7, 'Municipio', 'Los Guayos'),
(7, 'Municipio', 'Miranda'),
(7, 'Municipio', 'Montalbán'),
(7, 'Municipio', 'Naguanagua'),
(7, 'Municipio', 'Puerto Cabello'),
(7, 'Municipio', 'San Diego'),
(7, 'Municipio', 'San Joaquín'),
(7, 'Municipio', 'Valencia'),
(8, 'Municipio', 'Anzoátegui'),
(8, 'Municipio', 'Tinaquillo'),
(8, 'Municipio', 'Girardot'),
(8, 'Municipio', 'Lima Blanco'),
(8, 'Municipio', 'Pao de San Juan Bautista'),
(8, 'Municipio', 'Ricaurte'),
(8, 'Municipio', 'Rómulo Gallegos'),
(8, 'Municipio', 'San Carlos'),
(8, 'Municipio', 'Tinaco'),
(9, 'Municipio', 'Antonio Díaz'),
(9, 'Municipio', 'Casacoima'),
(9, 'Municipio', 'Pedernales'),
(9, 'Municipio', 'Tucupita'),
(10, 'Municipio', 'Acosta'),
(10, 'Municipio', 'Bolívar'),
(10, 'Municipio', 'Buchivacoa'),
(10, 'Municipio', 'Cacique Manaure'),
(10, 'Municipio', 'Carirubana'),
(10, 'Municipio', 'Colina'),
(10, 'Municipio', 'Dabajuro'),
(10, 'Municipio', 'Democracia'),
(10, 'Municipio', 'Falcón'),
(10, 'Municipio', 'Federación'),
(10, 'Municipio', 'Jacura'),
(10, 'Municipio', 'José Laurencio Silva'),
(10, 'Municipio', 'Los Taques'),
(10, 'Municipio', 'Mauroa'),
(10, 'Municipio', 'Miranda'),
(10, 'Municipio', 'Monseñor Iturriza'),
(10, 'Municipio', 'Palmasola'),
(10, 'Municipio', 'Petit'),
(10, 'Municipio', 'Píritu'),
(10, 'Municipio', 'San Francisco'),
(10, 'Municipio', 'Sucre'),
(10, 'Municipio', 'Tocópero'),
(10, 'Municipio', 'Unión'),
(10, 'Municipio', 'Urumaco'),
(10, 'Municipio', 'Zamora'),
(11, 'Municipio', 'Camaguán'),
(11, 'Municipio', 'Chaguaramas'),
(11, 'Municipio', 'El Socorro'),
(11, 'Municipio', 'José Félix Ribas'),
(11, 'Municipio', 'José Tadeo Monagas'),
(11, 'Municipio', 'Juan Germán Roscio'),
(11, 'Municipio', 'Julián Mellado'),
(11, 'Municipio', 'Las Mercedes'),
(11, 'Municipio', 'Leonardo Infante'),
(11, 'Municipio', 'Pedro Zaraza'),
(11, 'Municipio', 'Ortíz'),
(11, 'Municipio', 'San Gerónimo de Guayabal'),
(11, 'Municipio', 'San José de Guaribe'),
(11, 'Municipio', 'Santa María de Ipire'),
(11, 'Municipio', 'Sebastián Francisco de Miranda'),
(12, 'Municipio', 'Andrés Eloy Blanco'),
(12, 'Municipio', 'Crespo'),
(12, 'Municipio', 'Iribarren'),
(12, 'Municipio', 'Jiménez'),
(12, 'Municipio', 'Morán'),
(12, 'Municipio', 'Palavecino'),
(12, 'Municipio', 'Simón Planas'),
(12, 'Municipio', 'Torres'),
(12, 'Municipio', 'Urdaneta'),
(13, 'Municipio', 'Alberto Adriani'),
(13, 'Municipio', 'Andrés Bello'),
(13, 'Municipio', 'Antonio Pinto Salinas'),
(13, 'Municipio', 'Aricagua'),
(13, 'Municipio', 'Arzobispo Chacón'),
(13, 'Municipio', 'Campo Elías'),
(13, 'Municipio', 'Caracciolo Parra Olmedo'),
(13, 'Municipio', 'Cardenal Quintero'),
(13, 'Municipio', 'Guaraque'),
(13, 'Municipio', 'Julio César Salas'),
(13, 'Municipio', 'Justo Briceño'),
(13, 'Municipio', 'Libertador'),
(13, 'Municipio', 'Miranda'),
(13, 'Municipio', 'Obispo Ramos de Lora'),
(13, 'Municipio', 'Padre Noguera'),
(13, 'Municipio', 'Pueblo Llano'),
(13, 'Municipio', 'Rangel'),
(13, 'Municipio', 'Rivas Dávila'),
(13, 'Municipio', 'Santos Marquina'),
(13, 'Municipio', 'Sucre'),
(13, 'Municipio', 'Tovar'),
(13, 'Municipio', 'Tulio Febres Cordero'),
(13, 'Municipio', 'Zea'),
(14, 'Municipio', 'Acevedo'),
(14, 'Municipio', 'Andrés Bello'),
(14, 'Municipio', 'Baruta'),
(14, 'Municipio', 'Brión'),
(14, 'Municipio', 'Buroz'),
(14, 'Municipio', 'Carrizal'),
(14, 'Municipio', 'Chacao'),
(14, 'Municipio', 'Cristóbal Rojas'),
(14, 'Municipio', 'El Hatillo'),
(14, 'Municipio', 'Guaicaipuro'),
(14, 'Municipio', 'Independencia'),
(14, 'Municipio', 'Lander'),
(14, 'Municipio', 'Los Salias'),
(14, 'Municipio', 'Páez'),
(14, 'Municipio', 'Paz Castillo'),
(14, 'Municipio', 'Pedro Gual'),
(14, 'Municipio', 'Plaza'),
(14, 'Municipio', 'Simón Bolívar'),
(14, 'Municipio', 'Sucre'),
(14, 'Municipio', 'Urdaneta'),
(14, 'Municipio', 'Zamora'),
(15, 'Municipio', 'Acosta'),
(15, 'Municipio', 'Aguasay'),
(15, 'Municipio', 'Bolívar'),
(15, 'Municipio', 'Caripe'),
(15, 'Municipio', 'Cedeño'),
(15, 'Municipio', 'Ezequiel Zamora'),
(15, 'Municipio', 'Libertador'),
(15, 'Municipio', 'Maturín'),
(15, 'Municipio', 'Piar'),
(15, 'Municipio', 'Punceres'),
(15, 'Municipio', 'Santa Bárbara'),
(15, 'Municipio', 'Sotillo'),
(15, 'Municipio', 'Uracoa'),
(16, 'Municipio', 'Antolín del Campo'),
(16, 'Municipio', 'Arismendi'),
(16, 'Municipio', 'García'),
(16, 'Municipio', 'Gómez'),
(16, 'Municipio', 'Maneiro'),
(16, 'Municipio', 'Marcano'),
(16, 'Municipio', 'Mariño'),
(16, 'Municipio', 'Península de Macanao'),
(16, 'Municipio', 'Tubores'),
(16, 'Municipio', 'Villalba'),
(16, 'Municipio', 'Díaz'),
(17, 'Municipio', 'Agua Blanca'),
(17, 'Municipio', 'Araure'),
(17, 'Municipio', 'Esteller'),
(17, 'Municipio', 'Guanare'),
(17, 'Municipio', 'Guanarito'),
(17, 'Municipio', 'Monseñor José Vicente de Unda'),
(17, 'Municipio', 'Ospino'),
(17, 'Municipio', 'Páez'),
(17, 'Municipio', 'Papelón'),
(17, 'Municipio', 'San Genaro de Boconoíto'),
(17, 'Municipio', 'San Rafael de Onoto'),
(17, 'Municipio', 'Santa Rosalía'),
(17, 'Municipio', 'Sucre'),
(17, 'Municipio', 'Turén'),
(18, 'Municipio', 'Andrés Eloy Blanco'),
(18, 'Municipio', 'Andrés Mata'),
(18, 'Municipio', 'Arismendi'),
(18, 'Municipio', 'Benítez'),
(18, 'Municipio', 'Bermúdez'),
(18, 'Municipio', 'Bolívar'),
(18, 'Municipio', 'Cajigal'),
(18, 'Municipio', 'Cruz Salmerón Acosta'),
(18, 'Municipio', 'Libertador'),
(18, 'Municipio', 'Mariño'),
(18, 'Municipio', 'Mejía'),
(18, 'Municipio', 'Montes'),
(18, 'Municipio', 'Ribero'),
(18, 'Municipio', 'Sucre'),
(18, 'Municipio', 'Valdéz'),
(19, 'Municipio', 'Andrés Bello'),
(19, 'Municipio', 'Antonio Rómulo Costa'),
(19, 'Municipio', 'Ayacucho'),
(19, 'Municipio', 'Bolívar'),
(19, 'Municipio', 'Cárdenas'),
(19, 'Municipio', 'Córdoba'),
(19, 'Municipio', 'Fernández Feo'),
(19, 'Municipio', 'Francisco de Miranda'),
(19, 'Municipio', 'García de Hevia'),
(19, 'Municipio', 'Guásimos'),
(19, 'Municipio', 'Independencia'),
(19, 'Municipio', 'Jáuregui'),
(19, 'Municipio', 'José María Vargas'),
(19, 'Municipio', 'Junín'),
(19, 'Municipio', 'Libertad'),
(19, 'Municipio', 'Libertador'),
(19, 'Municipio', 'Lobatera'),
(19, 'Municipio', 'Michelena'),
(19, 'Municipio', 'Panamericano'),
(19, 'Municipio', 'Pedro María Ureña'),
(19, 'Municipio', 'Rafael Urdaneta'),
(19, 'Municipio', 'Samuel Darío Maldonado'),
(19, 'Municipio', 'San Cristóbal'),
(19, 'Municipio', 'Seboruco'),
(19, 'Municipio', 'Simón Rodríguez'),
(19, 'Municipio', 'Sucre'),
(19, 'Municipio', 'Torbes'),
(19, 'Municipio', 'Uribante'),
(19, 'Municipio', 'San Judas Tadeo'),
(20, 'Municipio', 'Andrés Bello'),
(20, 'Municipio', 'Boconó'),
(20, 'Municipio', 'Bolívar'),
(20, 'Municipio', 'Candelaria'),
(20, 'Municipio', 'Carache'),
(20, 'Municipio', 'Escuque'),
(20, 'Municipio', 'José Felipe Márquez Cañizalez'),
(20, 'Municipio', 'Juan Vicente Campos Elías'),
(20, 'Municipio', 'La Ceiba'),
(20, 'Municipio', 'Miranda'),
(20, 'Municipio', 'Monte Carmelo'),
(20, 'Municipio', 'Motatán'),
(20, 'Municipio', 'Pampán'),
(20, 'Municipio', 'Pampanito'),
(20, 'Municipio', 'Rafael Rangel'),
(20, 'Municipio', 'San Rafael de Carvajal'),
(20, 'Municipio', 'Sucre'),
(20, 'Municipio', 'Trujillo'),
(20, 'Municipio', 'Urdaneta'),
(20, 'Municipio', 'Valera'),
(21, 'Municipio', 'Vargas'),
(22, 'Municipio', 'Arístides Bastidas'),
(22, 'Municipio', 'Bolívar'),
(22, 'Municipio', 'Bruzual'),
(22, 'Municipio', 'Cocorote'),
(22, 'Municipio', 'Independencia'),
(22, 'Municipio', 'José Antonio Páez'),
(22, 'Municipio', 'La Trinidad'),
(22, 'Municipio', 'Manuel Monge'),
(22, 'Municipio', 'Nirgua'),
(22, 'Municipio', 'Peña'),
(22, 'Municipio', 'San Felipe'),
(22, 'Municipio', 'Sucre'),
(22, 'Municipio', 'Urachiche'),
(22, 'Municipio', 'José Joaquín Veroes'),
(23, 'Municipio', 'Almirante Padilla'),
(23, 'Municipio', 'Baralt'),
(23, 'Municipio', 'Cabimas'),
(23, 'Municipio', 'Catatumbo'),
(23, 'Municipio', 'Colón'),
(23, 'Municipio', 'Francisco Javier Pulgar'),
(23, 'Municipio', 'Páez'),
(23, 'Municipio', 'Jesús Enrique Losada'),
(23, 'Municipio', 'Jesús María Semprún'),
(23, 'Municipio', 'La Cañada de Urdaneta'),
(23, 'Municipio', 'Lagunillas'),
(23, 'Municipio', 'Machiques de Perijá'),
(23, 'Municipio', 'Mara'),
(23, 'Municipio', 'Maracaibo'),
(23, 'Municipio', 'Miranda'),
(23, 'Municipio', 'Rosario de Perijá'),
(23, 'Municipio', 'San Francisco'),
(23, 'Municipio', 'Santa Rita'),
(23, 'Municipio', 'Simón Bolívar'),
(23, 'Municipio', 'Sucre'),
(23, 'Municipio', 'Valmore Rodríguez'),
(24, 'Municipio', 'Libertador');

/* CIUDADES */
INSERT INTO Lugar (fk_lugar, tipo, nombre) VALUES
(1, 'Ciudad', 'Maroa'),
(1, 'Ciudad', 'Puerto Ayacucho'),
(1, 'Ciudad', 'San Fernando de Atabapo'),
(2, 'Ciudad', 'Anaco'),
(2, 'Ciudad', 'Aragua de Barcelona'),
(2, 'Ciudad', 'Barcelona'),
(2, 'Ciudad', 'Boca de Uchire'),
(2, 'Ciudad', 'Cantaura'),
(2, 'Ciudad', 'Clarines'),
(2, 'Ciudad', 'El Chaparro'),
(2, 'Ciudad', 'El Pao Anzoátegui'),
(2, 'Ciudad', 'El Tigre'),
(2, 'Ciudad', 'El Tigrito'),
(2, 'Ciudad', 'Guanape'),
(2, 'Ciudad', 'Guanta'),
(2, 'Ciudad', 'Lechería'),
(2, 'Ciudad', 'Onoto'),
(2, 'Ciudad', 'Pariaguán'),
(2, 'Ciudad', 'Píritu'),
(2, 'Ciudad', 'Puerto La Cruz'),
(2, 'Ciudad', 'Puerto Píritu'),
(2, 'Ciudad', 'Sabana de Uchire'),
(2, 'Ciudad', 'San Mateo Anzoátegui'),
(2, 'Ciudad', 'San Pablo Anzoátegui'),
(2, 'Ciudad', 'San Tomé'),
(2, 'Ciudad', 'Santa Ana de Anzoátegui'),
(2, 'Ciudad', 'Santa Fe Anzoátegui'),
(2, 'Ciudad', 'Santa Rosa'),
(2, 'Ciudad', 'Soledad'),
(2, 'Ciudad', 'Urica'),
(2, 'Ciudad', 'Valle de Guanape'),
(3, 'Ciudad', 'Achaguas'),
(3, 'Ciudad', 'Biruaca'),
(3, 'Ciudad', 'Bruzual'),
(3, 'Ciudad', 'El Amparo'),
(3, 'Ciudad', 'El Nula'),
(3, 'Ciudad', 'Elorza'),
(3, 'Ciudad', 'Guasdualito'),
(3, 'Ciudad', 'Mantecal'),
(3, 'Ciudad', 'Puerto Páez'),
(3, 'Ciudad', 'San Fernando de Apure'),
(3, 'Ciudad', 'San Juan de Payara'),
(4, 'Ciudad', 'Barbacoas'),
(4, 'Ciudad', 'Cagua'),
(4, 'Ciudad', 'Camatagua'),
(4, 'Ciudad', 'Choroní'),
(4, 'Ciudad', 'Colonia Tovar'),
(4, 'Ciudad', 'El Consejo'),
(4, 'Ciudad', 'La Victoria'),
(4, 'Ciudad', 'Las Tejerías'),
(4, 'Ciudad', 'Magdaleno'),
(4, 'Ciudad', 'Maracay'),
(4, 'Ciudad', 'Ocumare de La Costa'),
(4, 'Ciudad', 'Palo Negro'),
(4, 'Ciudad', 'San Casimiro'),
(4, 'Ciudad', 'San Mateo'),
(4, 'Ciudad', 'San Sebastián'),
(4, 'Ciudad', 'Santa Cruz de Aragua'),
(4, 'Ciudad', 'Tocorón'),
(4, 'Ciudad', 'Turmero'),
(4, 'Ciudad', 'Villa de Cura'),
(4, 'Ciudad', 'Zuata'),
(5, 'Ciudad', 'Barinas'),
(5, 'Ciudad', 'Barinitas'),
(5, 'Ciudad', 'Barrancas'),
(5, 'Ciudad', 'Calderas'),
(5, 'Ciudad', 'Capitanejo'),
(5, 'Ciudad', 'Ciudad Bolivia'),
(5, 'Ciudad', 'El Cantón'),
(5, 'Ciudad', 'Las Veguitas'),
(5, 'Ciudad', 'Libertad de Barinas'),
(5, 'Ciudad', 'Sabaneta'),
(5, 'Ciudad', 'Santa Bárbara de Barinas'),
(5, 'Ciudad', 'Socopó'),
(6, 'Ciudad', 'Caicara del Orinoco'),
(6, 'Ciudad', 'Canaima'),
(6, 'Ciudad', 'Ciudad Bolívar'),
(6, 'Ciudad', 'Ciudad Piar'),
(6, 'Ciudad', 'El Callao'),
(6, 'Ciudad', 'El Dorado'),
(6, 'Ciudad', 'El Manteco'),
(6, 'Ciudad', 'El Palmar'),
(6, 'Ciudad', 'El Pao'),
(6, 'Ciudad', 'Guasipati'),
(6, 'Ciudad', 'Guri'),
(6, 'Ciudad', 'La Paragua'),
(6, 'Ciudad', 'Matanzas'),
(6, 'Ciudad', 'Puerto Ordaz'),
(6, 'Ciudad', 'San Félix'),
(6, 'Ciudad', 'Santa Elena de Uairén'),
(6, 'Ciudad', 'Tumeremo'),
(6, 'Ciudad', 'Unare'),
(6, 'Ciudad', 'Upata'),
(7, 'Ciudad', 'Bejuma'),
(7, 'Ciudad', 'Belén'),
(7, 'Ciudad', 'Campo de Carabobo'),
(7, 'Ciudad', 'Canoabo'),
(7, 'Ciudad', 'Central Tacarigua'),
(7, 'Ciudad', 'Chirgua'),
(7, 'Ciudad', 'Ciudad Alianza'),
(7, 'Ciudad', 'El Palito'),
(7, 'Ciudad', 'Guacara'),
(7, 'Ciudad', 'Guigue'),
(7, 'Ciudad', 'Las Trincheras'),
(7, 'Ciudad', 'Los Guayos'),
(7, 'Ciudad', 'Mariara'),
(7, 'Ciudad', 'Miranda'),
(7, 'Ciudad', 'Montalbán'),
(7, 'Ciudad', 'Morón'),
(7, 'Ciudad', 'Naguanagua'),
(7, 'Ciudad', 'Puerto Cabello'),
(7, 'Ciudad', 'San Joaquín'),
(7, 'Ciudad', 'Tocuyito'),
(7, 'Ciudad', 'Urama'),
(7, 'Ciudad', 'Valencia'),
(7, 'Ciudad', 'Vigirimita'),
(8, 'Ciudad', 'Aguirre'),
(8, 'Ciudad', 'Apartaderos Cojedes'),
(8, 'Ciudad', 'Arismendi'),
(8, 'Ciudad', 'Camuriquito'),
(8, 'Ciudad', 'El Baúl'),
(8, 'Ciudad', 'El Limón'),
(8, 'Ciudad', 'El Pao Cojedes'),
(8, 'Ciudad', 'El Socorro'),
(8, 'Ciudad', 'La Aguadita'),
(8, 'Ciudad', 'Las Vegas'),
(8, 'Ciudad', 'Libertad de Cojedes'),
(8, 'Ciudad', 'Mapuey'),
(8, 'Ciudad', 'Piñedo'),
(8, 'Ciudad', 'Samancito'),
(8, 'Ciudad', 'San Carlos'),
(8, 'Ciudad', 'Sucre'),
(8, 'Ciudad', 'Tinaco'),
(8, 'Ciudad', 'Tinaquillo'),
(8, 'Ciudad', 'Vallecito'),
(9, 'Ciudad', 'Tucupita'),
(24, 'Ciudad', 'Caracas'),
(24, 'Ciudad', 'El Junquito'),
(10, 'Ciudad', 'Adícora'),
(10, 'Ciudad', 'Boca de Aroa'),
(10, 'Ciudad', 'Cabure'),
(10, 'Ciudad', 'Capadare'),
(10, 'Ciudad', 'Capatárida'),
(10, 'Ciudad', 'Chichiriviche'),
(10, 'Ciudad', 'Churuguara'),
(10, 'Ciudad', 'Coro'),
(10, 'Ciudad', 'Cumarebo'),
(10, 'Ciudad', 'Dabajuro'),
(10, 'Ciudad', 'Judibana'),
(10, 'Ciudad', 'La Cruz de Taratara'),
(10, 'Ciudad', 'La Vela de Coro'),
(10, 'Ciudad', 'Los Taques'),
(10, 'Ciudad', 'Maparari'),
(10, 'Ciudad', 'Mene de Mauroa'),
(10, 'Ciudad', 'Mirimire'),
(10, 'Ciudad', 'Pedregal'),
(10, 'Ciudad', 'Píritu Falcón'),
(10, 'Ciudad', 'Pueblo Nuevo Falcón'),
(10, 'Ciudad', 'Puerto Cumarebo'),
(10, 'Ciudad', 'Punta Cardón'),
(10, 'Ciudad', 'Punto Fijo'),
(10, 'Ciudad', 'San Juan de Los Cayos'),
(10, 'Ciudad', 'San Luis'),
(10, 'Ciudad', 'Santa Ana Falcón'),
(10, 'Ciudad', 'Santa Cruz De Bucaral'),
(10, 'Ciudad', 'Tocopero'),
(10, 'Ciudad', 'Tocuyo de La Costa'),
(10, 'Ciudad', 'Tucacas'),
(10, 'Ciudad', 'Yaracal'),
(11, 'Ciudad', 'Altagracia de Orituco'),
(11, 'Ciudad', 'Cabruta'),
(11, 'Ciudad', 'Calabozo'),
(11, 'Ciudad', 'Camaguán'),
(11, 'Ciudad', 'Chaguaramas Guárico'),
(11, 'Ciudad', 'El Socorro'),
(11, 'Ciudad', 'El Sombrero'),
(11, 'Ciudad', 'Las Mercedes de Los Llanos'),
(11, 'Ciudad', 'Lezama'),
(11, 'Ciudad', 'Onoto'),
(11, 'Ciudad', 'Ortíz'),
(11, 'Ciudad', 'San José de Guaribe'),
(11, 'Ciudad', 'San Juan de Los Morros'),
(11, 'Ciudad', 'San Rafael de Laya'),
(11, 'Ciudad', 'Santa María de Ipire'),
(11, 'Ciudad', 'Tucupido'),
(11, 'Ciudad', 'Valle de La Pascua'),
(11, 'Ciudad', 'Zaraza'),
(12, 'Ciudad', 'Aguada Grande'),
(12, 'Ciudad', 'Atarigua'),
(12, 'Ciudad', 'Barquisimeto'),
(12, 'Ciudad', 'Bobare'),
(12, 'Ciudad', 'Cabudare'),
(12, 'Ciudad', 'Carora'),
(12, 'Ciudad', 'Cubiro'),
(12, 'Ciudad', 'Cují'),
(12, 'Ciudad', 'Duaca'),
(12, 'Ciudad', 'El Manzano'),
(12, 'Ciudad', 'El Tocuyo'),
(12, 'Ciudad', 'Guaríco'),
(12, 'Ciudad', 'Humocaro Alto'),
(12, 'Ciudad', 'Humocaro Bajo'),
(12, 'Ciudad', 'La Miel'),
(12, 'Ciudad', 'Moroturo'),
(12, 'Ciudad', 'Quíbor'),
(12, 'Ciudad', 'Río Claro'),
(12, 'Ciudad', 'Sanare'),
(12, 'Ciudad', 'Santa Inés'),
(12, 'Ciudad', 'Sarare'),
(12, 'Ciudad', 'Siquisique'),
(12, 'Ciudad', 'Tintorero'),
(13, 'Ciudad', 'Apartaderos Mérida'),
(13, 'Ciudad', 'Arapuey'),
(13, 'Ciudad', 'Bailadores'),
(13, 'Ciudad', 'Caja Seca'),
(13, 'Ciudad', 'Canaguá'),
(13, 'Ciudad', 'Chachopo'),
(13, 'Ciudad', 'Chiguara'),
(13, 'Ciudad', 'Ejido'),
(13, 'Ciudad', 'El Vigía'),
(13, 'Ciudad', 'La Azulita'),
(13, 'Ciudad', 'La Playa'),
(13, 'Ciudad', 'Lagunillas Mérida'),
(13, 'Ciudad', 'Mérida'),
(13, 'Ciudad', 'Mesa de Bolívar'),
(13, 'Ciudad', 'Mucuchíes'),
(13, 'Ciudad', 'Mucujepe'),
(13, 'Ciudad', 'Mucuruba'),
(13, 'Ciudad', 'Nueva Bolivia'),
(13, 'Ciudad', 'Palmarito'),
(13, 'Ciudad', 'Pueblo Llano'),
(13, 'Ciudad', 'Santa Cruz de Mora'),
(13, 'Ciudad', 'Santa Elena de Arenales'),
(13, 'Ciudad', 'Santo Domingo'),
(13, 'Ciudad', 'Tabáy'),
(13, 'Ciudad', 'Timotes'),
(13, 'Ciudad', 'Torondoy'),
(13, 'Ciudad', 'Tovar'),
(13, 'Ciudad', 'Tucani'),
(13, 'Ciudad', 'Zea'),
(14, 'Ciudad', 'Araguita'),
(14, 'Ciudad', 'Carrizal'),
(14, 'Ciudad', 'Caucagua'),
(14, 'Ciudad', 'Chaguaramas Miranda'),
(14, 'Ciudad', 'Charallave'),
(14, 'Ciudad', 'Chirimena'),
(14, 'Ciudad', 'Chuspa'),
(14, 'Ciudad', 'Cúa'),
(14, 'Ciudad', 'Cupira'),
(14, 'Ciudad', 'Curiepe'),
(14, 'Ciudad', 'El Guapo'),
(14, 'Ciudad', 'El Jarillo'),
(14, 'Ciudad', 'Filas de Mariche'),
(14, 'Ciudad', 'Guarenas'),
(14, 'Ciudad', 'Guatire'),
(14, 'Ciudad', 'Higuerote'),
(14, 'Ciudad', 'Los Anaucos'),
(14, 'Ciudad', 'Los Teques'),
(14, 'Ciudad', 'Ocumare del Tuy'),
(14, 'Ciudad', 'Panaquire'),
(14, 'Ciudad', 'Paracotos'),
(14, 'Ciudad', 'Río Chico'),
(14, 'Ciudad', 'San Antonio de Los Altos'),
(14, 'Ciudad', 'San Diego de Los Altos'),
(14, 'Ciudad', 'San Fernando del Guapo'),
(14, 'Ciudad', 'San Francisco de Yare'),
(14, 'Ciudad', 'San José de Los Altos'),
(14, 'Ciudad', 'San José de Río Chico'),
(14, 'Ciudad', 'San Pedro de Los Altos'),
(14, 'Ciudad', 'Santa Lucía'),
(14, 'Ciudad', 'Santa Teresa'),
(14, 'Ciudad', 'Tacarigua de La Laguna'),
(14, 'Ciudad', 'Tacarigua de Mamporal'),
(14, 'Ciudad', 'Tácata'),
(14, 'Ciudad', 'Turumo'),
(15, 'Ciudad', 'Aguasay'),
(15, 'Ciudad', 'Aragua de Maturín'),
(15, 'Ciudad', 'Barrancas del Orinoco'),
(15, 'Ciudad', 'Caicara de Maturín'),
(15, 'Ciudad', 'Caripe'),
(15, 'Ciudad', 'Caripito'),
(15, 'Ciudad', 'Chaguaramal'),
(15, 'Ciudad', 'Chaguaramas Monagas'),
(15, 'Ciudad', 'El Furrial'),
(15, 'Ciudad', 'El Tejero'),
(15, 'Ciudad', 'Jusepín'),
(15, 'Ciudad', 'La Toscana'),
(15, 'Ciudad', 'Maturín'),
(15, 'Ciudad', 'Miraflores'),
(15, 'Ciudad', 'Punta de Mata'),
(15, 'Ciudad', 'Quiriquire'),
(15, 'Ciudad', 'San Antonio de Maturín'),
(15, 'Ciudad', 'San Vicente Monagas'),
(15, 'Ciudad', 'Santa Bárbara'),
(15, 'Ciudad', 'Temblador'),
(15, 'Ciudad', 'Teresen'),
(15, 'Ciudad', 'Uracoa'),
(16, 'Ciudad', 'Altagracia'),
(16, 'Ciudad', 'Boca de Pozo'),
(16, 'Ciudad', 'Boca de Río'),
(16, 'Ciudad', 'El Espinal'),
(16, 'Ciudad', 'El Valle del Espíritu Santo'),
(16, 'Ciudad', 'El Yaque'),
(16, 'Ciudad', 'Juangriego'),
(16, 'Ciudad', 'La Asunción'),
(16, 'Ciudad', 'La Guardia'),
(16, 'Ciudad', 'Pampatar'),
(16, 'Ciudad', 'Porlamar'),
(16, 'Ciudad', 'Puerto Fermín'),
(16, 'Ciudad', 'Punta de Piedras'),
(16, 'Ciudad', 'San Francisco de Macanao'),
(16, 'Ciudad', 'San Juan Bautista'),
(16, 'Ciudad', 'San Pedro de Coche'),
(16, 'Ciudad', 'Santa Ana de Nueva Esparta'),
(16, 'Ciudad', 'Villa Rosa'),
(17, 'Ciudad', 'Acarigua'),
(17, 'Ciudad', 'Agua Blanca'),
(17, 'Ciudad', 'Araure'),
(17, 'Ciudad', 'Biscucuy'),
(17, 'Ciudad', 'Boconoito'),
(17, 'Ciudad', 'Campo Elías'),
(17, 'Ciudad', 'Chabasquén'),
(17, 'Ciudad', 'Guanare'),
(17, 'Ciudad', 'Guanarito'),
(17, 'Ciudad', 'La Aparición'),
(17, 'Ciudad', 'La Misión'),
(17, 'Ciudad', 'Mesa de Cavacas'),
(17, 'Ciudad', 'Ospino'),
(17, 'Ciudad', 'Papelón'),
(17, 'Ciudad', 'Payara'),
(17, 'Ciudad', 'Pimpinela'),
(17, 'Ciudad', 'Píritu de Portuguesa'),
(17, 'Ciudad', 'San Rafael de Onoto'),
(17, 'Ciudad', 'Santa Rosalía'),
(17, 'Ciudad', 'Turén'),
(18, 'Ciudad', 'Altos de Sucre'),
(18, 'Ciudad', 'Araya'),
(18, 'Ciudad', 'Cariaco'),
(18, 'Ciudad', 'Carúpano'),
(18, 'Ciudad', 'Casanay'),
(18, 'Ciudad', 'Cumaná'),
(18, 'Ciudad', 'Cumanacoa'),
(18, 'Ciudad', 'El Morro Puerto Santo'),
(18, 'Ciudad', 'El Pilar'),
(18, 'Ciudad', 'El Poblado'),
(18, 'Ciudad', 'Guaca'),
(18, 'Ciudad', 'Guiria'),
(18, 'Ciudad', 'Irapa'),
(18, 'Ciudad', 'Manicuare'),
(18, 'Ciudad', 'Mariguitar'),
(18, 'Ciudad', 'Río Caribe'),
(18, 'Ciudad', 'San Antonio del Golfo'),
(18, 'Ciudad', 'San José de Aerocuar'),
(18, 'Ciudad', 'San Vicente de Sucre'),
(18, 'Ciudad', 'Santa Fe de Sucre'),
(18, 'Ciudad', 'Tunapuy'),
(18, 'Ciudad', 'Yaguaraparo'),
(18, 'Ciudad', 'Yoco'),
(19, 'Ciudad', 'Abejales'),
(19, 'Ciudad', 'Borota'),
(19, 'Ciudad', 'Bramon'),
(19, 'Ciudad', 'Capacho'),
(19, 'Ciudad', 'Colón'),
(19, 'Ciudad', 'Coloncito'),
(19, 'Ciudad', 'Cordero'),
(19, 'Ciudad', 'El Cobre'),
(19, 'Ciudad', 'El Pinal'),
(19, 'Ciudad', 'Independencia'),
(19, 'Ciudad', 'La Fría'),
(19, 'Ciudad', 'La Grita'),
(19, 'Ciudad', 'La Pedrera'),
(19, 'Ciudad', 'La Tendida'),
(19, 'Ciudad', 'Las Delicias'),
(19, 'Ciudad', 'Las Hernández'),
(19, 'Ciudad', 'Lobatera'),
(19, 'Ciudad', 'Michelena'),
(19, 'Ciudad', 'Palmira'),
(19, 'Ciudad', 'Pregonero'),
(19, 'Ciudad', 'Queniquea'),
(19, 'Ciudad', 'Rubio'),
(19, 'Ciudad', 'San Antonio del Tachira'),
(19, 'Ciudad', 'San Cristobal'),
(19, 'Ciudad', 'San José de Bolívar'),
(19, 'Ciudad', 'San Josecito'),
(19, 'Ciudad', 'San Pedro del Río'),
(19, 'Ciudad', 'Santa Ana Táchira'),
(19, 'Ciudad', 'Seboruco'),
(19, 'Ciudad', 'Táriba'),
(19, 'Ciudad', 'Umuquena'),
(19, 'Ciudad', 'Ureña'),
(20, 'Ciudad', 'Batatal'),
(20, 'Ciudad', 'Betijoque'),
(20, 'Ciudad', 'Boconó'),
(20, 'Ciudad', 'Carache'),
(20, 'Ciudad', 'Chejende'),
(20, 'Ciudad', 'Cuicas'),
(20, 'Ciudad', 'El Dividive'),
(20, 'Ciudad', 'El Jaguito'),
(20, 'Ciudad', 'Escuque'),
(20, 'Ciudad', 'Isnotú'),
(20, 'Ciudad', 'Jajó'),
(20, 'Ciudad', 'La Ceiba'),
(20, 'Ciudad', 'La Concepción de Trujllo'),
(20, 'Ciudad', 'La Mesa de Esnujaque'),
(20, 'Ciudad', 'La Puerta'),
(20, 'Ciudad', 'La Quebrada'),
(20, 'Ciudad', 'Mendoza Fría'),
(20, 'Ciudad', 'Meseta de Chimpire'),
(20, 'Ciudad', 'Monay'),
(20, 'Ciudad', 'Motatán'),
(20, 'Ciudad', 'Pampán'),
(20, 'Ciudad', 'Pampanito'),
(20, 'Ciudad', 'Sabana de Mendoza'),
(20, 'Ciudad', 'San Lázaro'),
(20, 'Ciudad', 'Santa Ana de Trujillo'),
(20, 'Ciudad', 'Tostós'),
(20, 'Ciudad', 'Trujillo'),
(20, 'Ciudad', 'Valera'),
(21, 'Ciudad', 'Carayaca'),
(21, 'Ciudad', 'Litoral'),
(25, 'Ciudad', 'Archipiélago Los Roques'),
(22, 'Ciudad', 'Aroa'),
(22, 'Ciudad', 'Boraure'),
(22, 'Ciudad', 'Campo Elías de Yaracuy'),
(22, 'Ciudad', 'Chivacoa'),
(22, 'Ciudad', 'Cocorote'),
(22, 'Ciudad', 'Farriar'),
(22, 'Ciudad', 'Guama'),
(22, 'Ciudad', 'Marín'),
(22, 'Ciudad', 'Nirgua'),
(22, 'Ciudad', 'Sabana de Parra'),
(22, 'Ciudad', 'Salom'),
(22, 'Ciudad', 'San Felipe'),
(22, 'Ciudad', 'San Pablo de Yaracuy'),
(22, 'Ciudad', 'Urachiche'),
(22, 'Ciudad', 'Yaritagua'),
(22, 'Ciudad', 'Yumare'),
(23, 'Ciudad', 'Bachaquero'),
(23, 'Ciudad', 'Bobures'),
(23, 'Ciudad', 'Cabimas'),
(23, 'Ciudad', 'Campo Concepción'),
(23, 'Ciudad', 'Campo Mara'),
(23, 'Ciudad', 'Campo Rojo'),
(23, 'Ciudad', 'Carrasquero'),
(23, 'Ciudad', 'Casigua'),
(23, 'Ciudad', 'Chiquinquirá'),
(23, 'Ciudad', 'Ciudad Ojeda'),
(23, 'Ciudad', 'El Batey'),
(23, 'Ciudad', 'El Carmelo'),
(23, 'Ciudad', 'El Chivo'),
(23, 'Ciudad', 'El Guayabo'),
(23, 'Ciudad', 'El Mene'),
(23, 'Ciudad', 'El Venado'),
(23, 'Ciudad', 'Encontrados'),
(23, 'Ciudad', 'Gibraltar'),
(23, 'Ciudad', 'Isla de Toas'),
(23, 'Ciudad', 'La Concepción del Zulia'),
(23, 'Ciudad', 'La Paz'),
(23, 'Ciudad', 'La Sierrita'),
(23, 'Ciudad', 'Lagunillas del Zulia'),
(23, 'Ciudad', 'Las Piedras de Perijá'),
(23, 'Ciudad', 'Los Cortijos'),
(23, 'Ciudad', 'Machiques'),
(23, 'Ciudad', 'Maracaibo'),
(23, 'Ciudad', 'Mene Grande'),
(23, 'Ciudad', 'Palmarejo'),
(23, 'Ciudad', 'Paraguaipoa'),
(23, 'Ciudad', 'Potrerito'),
(23, 'Ciudad', 'Pueblo Nuevo del Zulia'),
(23, 'Ciudad', 'Puertos de Altagracia'),
(23, 'Ciudad', 'Punta Gorda'),
(23, 'Ciudad', 'Sabaneta de Palma'),
(23, 'Ciudad', 'San Francisco'),
(23, 'Ciudad', 'San José de Perijá'),
(23, 'Ciudad', 'San Rafael del Moján'),
(23, 'Ciudad', 'San Timoteo'),
(23, 'Ciudad', 'Santa Bárbara Del Zulia'),
(23, 'Ciudad', 'Santa Cruz de Mara'),
(23, 'Ciudad', 'Santa Cruz del Zulia'),
(23, 'Ciudad', 'Santa Rita'),
(23, 'Ciudad', 'Sinamaica'),
(23, 'Ciudad', 'Tamare'),
(23, 'Ciudad', 'Tía Juana'),
(23, 'Ciudad', 'Villa del Rosario'),
(21, 'Ciudad', 'La Guaira'),
(21, 'Ciudad', 'Catia La Mar'),
(21, 'Ciudad', 'Macuto'),
(21, 'Ciudad', 'Naiguatá'),
(25, 'Ciudad', 'Archipiélago Los Monjes'),
(25, 'Ciudad', 'Isla La Tortuga y Cayos adyacentes'),
(25, 'Ciudad', 'Isla La Sola'),
(25, 'Ciudad', 'Islas Los Testigos'),
(25, 'Ciudad', 'Islas Los Frailes'),
(25, 'Ciudad', 'Isla La Orchila'),
(25, 'Ciudad', 'Archipiélago Las Aves'),
(25, 'Ciudad', 'Isla de Aves'),
(25, 'Ciudad', 'Isla La Blanquilla'),
(25, 'Ciudad', 'Isla de Patos'),
(25, 'Ciudad', 'Islas Los Hermanos');

INSERT INTO Lugar (fk_lugar, tipo, nombre) VALUES
(26, 'Parroquia', 'Alto Orinoco'),
(26, 'Parroquia', 'Huachamacare Acanaña'),
(26, 'Parroquia', 'Marawaka Toky Shamanaña'),
(26, 'Parroquia', 'Mavaka Mavaka'),
(26, 'Parroquia', 'Sierra Parima Parimabé'),
(27, 'Parroquia', 'Ucata Laja Lisa'),
(27, 'Parroquia', 'Yapacana Macuruco'),
(27, 'Parroquia', 'Caname Guarinuma'),
(28, 'Parroquia', 'Fernando Girón Tovar'),
(28, 'Parroquia', 'Luis Alberto Gómez'),
(28, 'Parroquia', 'Pahueña Limón de Parhueña'),
(28, 'Parroquia', 'Platanillal Platanillal'),
(29, 'Parroquia', 'Samariapo'),
(29, 'Parroquia', 'Sipapo'),
(29, 'Parroquia', 'Munduapo'),
(29, 'Parroquia', 'Guayapo'),
(30, 'Parroquia', 'Alto Ventuari'),
(30, 'Parroquia', 'Medio Ventuari'),
(30, 'Parroquia', 'Bajo Ventuari'),
(31, 'Parroquia', 'Victorino'),
(31, 'Parroquia', 'Comunidad'),
(32, 'Parroquia', 'Casiquiare'),
(32, 'Parroquia', 'Cocuy'),
(32, 'Parroquia', 'San Carlos de Río Negro'),
(32, 'Parroquia', 'Solano'),
(33, 'Parroquia', 'Anaco'),
(33, 'Parroquia', 'San Joaquín'),
(34, 'Parroquia', 'Cachipo'),
(34, 'Parroquia', 'Aragua de Barcelona'),
(36, 'Parroquia', 'Lechería'),
(36, 'Parroquia', 'El Morro'),
(37, 'Parroquia', 'Puerto Píritu'),
(37, 'Parroquia', 'San Miguel'),
(37, 'Parroquia', 'Sucre'),
(38, 'Parroquia', 'Valle de Guanape'),
(38, 'Parroquia', 'Santa Bárbara'),
(39, 'Parroquia', 'El Chaparro'),
(39, 'Parroquia', 'Tomás Alfaro'),
(39, 'Parroquia', 'Calatrava'),
(40, 'Parroquia', 'Guanta'),
(40, 'Parroquia', 'Chorrerón'),
(41, 'Parroquia', 'Mamo'),
(41, 'Parroquia', 'Soledad'),
(42, 'Parroquia', 'Mapire'),
(42, 'Parroquia', 'Piar'),
(42, 'Parroquia', 'Santa Clara'),
(42, 'Parroquia', 'San Diego de Cabrutica'),
(42, 'Parroquia', 'Uverito'),
(42, 'Parroquia', 'Zuata'),
(43, 'Parroquia', 'Puerto La Cruz'),
(43, 'Parroquia', 'Pozuelos'),
(44, 'Parroquia', 'Onoto'),
(44, 'Parroquia', 'San Pablo'),
(45, 'Parroquia', 'San Mateo'),
(45, 'Parroquia', 'El Carito'),
(45, 'Parroquia', 'Santa Inés'),
(45, 'Parroquia', 'La Romereña'),
(46, 'Parroquia', 'Atapirire'),
(46, 'Parroquia', 'Boca del Pao'),
(46, 'Parroquia', 'El Pao'),
(46, 'Parroquia', 'Pariaguán'),
(47, 'Parroquia', 'Cantaura'),
(47, 'Parroquia', 'Libertador'),
(47, 'Parroquia', 'Santa Rosa'),
(47, 'Parroquia', 'Urica'),
(48, 'Parroquia', 'Píritu'),
(48, 'Parroquia', 'San Francisco'),
(49, 'Parroquia', 'San José de Guanipa'),
(50, 'Parroquia', 'Boca de Uchire'),
(50, 'Parroquia', 'Boca de Chávez'),
(51, 'Parroquia', 'Pueblo Nuevo'),
(51, 'Parroquia', 'Santa Ana'),
(52, 'Parroquia', 'Bergantín'),
(52, 'Parroquia', 'Caigua'),
(52, 'Parroquia', 'El Carmen'),
(52, 'Parroquia', 'El Pilar'),
(52, 'Parroquia', 'Naricual'),
(52, 'Parroquia', 'San Crsitóbal'),
(53, 'Parroquia', 'Edmundo Barrios'),
(53, 'Parroquia', 'Miguel Otero Silva'),
(54, 'Parroquia', 'Achaguas'),
(54, 'Parroquia', 'Apurito'),
(54, 'Parroquia', 'El Yagual'),
(54, 'Parroquia', 'Guachara'),
(54, 'Parroquia', 'Mucuritas'),
(54, 'Parroquia', 'Queseras del medio'),
(55, 'Parroquia', 'Biruaca'),
(56, 'Parroquia', 'Bruzual'),
(56, 'Parroquia', 'Mantecal'),
(56, 'Parroquia', 'Quintero'),
(56, 'Parroquia', 'Rincón Hondo'),
(56, 'Parroquia', 'San Vicente'),
(57, 'Parroquia', 'Guasdualito'),
(57, 'Parroquia', 'Aramendi'),
(57, 'Parroquia', 'El Amparo'),
(57, 'Parroquia', 'San Camilo'),
(57, 'Parroquia', 'Urdaneta'),
(58, 'Parroquia', 'San Juan de Payara'),
(58, 'Parroquia', 'Codazzi'),
(58, 'Parroquia', 'Cunaviche'),
(59, 'Parroquia', 'Elorza'),
(59, 'Parroquia', 'La Trinidad'),
(60, 'Parroquia', 'San Fernando'),
(60, 'Parroquia', 'El Recreo'),
(60, 'Parroquia', 'Peñalver'),
(60, 'Parroquia', 'San Rafael de Atamaica'),
(61, 'Parroquia', 'Pedro José Ovalles'),
(61, 'Parroquia', 'Joaquín Crespo'),
(61, 'Parroquia', 'José Casanova Godoy'),
(61, 'Parroquia', 'Madre María de San José'),
(61, 'Parroquia', 'Andrés Eloy Blanco'),
(61, 'Parroquia', 'Los Tacarigua'),
(61, 'Parroquia', 'Las Delicias'),
(61, 'Parroquia', 'Choroní'),
(62, 'Parroquia', 'Bolívar'),
(63, 'Parroquia', 'Camatagua'),
(63, 'Parroquia', 'Carmen de Cura'),
(64, 'Parroquia', 'Santa Rita'),
(64, 'Parroquia', 'Francisco de Miranda'),
(64, 'Parroquia', 'Moseñor Feliciano González'),
(65, 'Parroquia', 'Santa Cruz'),
(66, 'Parroquia', 'José Félix Ribas'),
(66, 'Parroquia', 'Castor Nieves Ríos'),
(66, 'Parroquia', 'Las Guacamayas'),
(66, 'Parroquia', 'Pao de Zárate'),
(66, 'Parroquia', 'Zuata'),
(67, 'Parroquia', 'José Rafael Revenga'),
(68, 'Parroquia', 'Palo Negro'),
(68, 'Parroquia', 'San Martín de Porres'),
(69, 'Parroquia', 'El Limón'),
(69, 'Parroquia', 'Caña de Azúcar'),
(70, 'Parroquia', 'Ocumare de la Costa'),
(71, 'Parroquia', 'San Casimiro'),
(71, 'Parroquia', 'Güiripa'),
(71, 'Parroquia', 'Ollas de Caramacate'),
(71, 'Parroquia', 'Valle Morín'),
(72, 'Parroquia', 'San Sebastían'),
(73, 'Parroquia', 'Turmero'),
(73, 'Parroquia', 'Arevalo Aponte'),
(73, 'Parroquia', 'Chuao'),
(73, 'Parroquia', 'Samán de Güere'),
(73, 'Parroquia', 'Alfredo Pacheco Miranda'),
(74, 'Parroquia', 'Santos Michelena'),
(74, 'Parroquia', 'Tiara'),
(75, 'Parroquia', 'Cagua'),
(75, 'Parroquia', 'Bella Vista'),
(76, 'Parroquia', 'Tovar'),
(77, 'Parroquia', 'Urdaneta'),
(77, 'Parroquia', 'Las Peñitas'),
(77, 'Parroquia', 'San Francisco de Cara'),
(77, 'Parroquia', 'Taguay'),
(78, 'Parroquia', 'Zamora'),
(78, 'Parroquia', 'Magdaleno'),
(78, 'Parroquia', 'San Francisco de Asís'),
(78, 'Parroquia', 'Valles de Tucutunemo'),
(78, 'Parroquia', 'Augusto Mijares'),
(79, 'Parroquia', 'Sabaneta'),
(79, 'Parroquia', 'Juan Antonio Rodríguez Domínguez'),
(80, 'Parroquia', 'El Cantón'),
(80, 'Parroquia', 'Santa Cruz de Guacas'),
(80, 'Parroquia', 'Puerto Vivas'),
(81, 'Parroquia', 'Ticoporo'),
(81, 'Parroquia', 'Nicolás Pulido'),
(81, 'Parroquia', 'Andrés Bello'),
(82, 'Parroquia', 'Arismendi'),
(82, 'Parroquia', 'Guadarrama'),
(82, 'Parroquia', 'La Unión'),
(82, 'Parroquia', 'San Antonio'),
(83, 'Parroquia', 'Barinas'),
(83, 'Parroquia', 'Alberto Arvelo Larriva'),
(83, 'Parroquia', 'San Silvestre'),
(83, 'Parroquia', 'Santa Inés'),
(83, 'Parroquia', 'Santa Lucía'),
(83, 'Parroquia', 'Torumos'),
(83, 'Parroquia', 'El Carmen'),
(83, 'Parroquia', 'Rómulo Betancourt'),
(83, 'Parroquia', 'Corazón de Jesús'),
(83, 'Parroquia', 'Ramón Ignacio Méndez'),
(83, 'Parroquia', 'Alto Barinas'),
(83, 'Parroquia', 'Manuel Palacio Fajardo'),
(83, 'Parroquia', 'Juan Antonio Rodríguez Domínguez'),
(83, 'Parroquia', 'Dominga Ortiz de Páez'),
(84, 'Parroquia', 'Barinitas'),
(84, 'Parroquia', 'Altamira de Cáceres'),
(84, 'Parroquia', 'Calderas'),
(85, 'Parroquia', 'Barrancas'),
(85, 'Parroquia', 'El Socorro'),
(85, 'Parroquia', 'Mazparrito'),
(86, 'Parroquia', 'Santa Bárbara'),
(86, 'Parroquia', 'Pedro Briceño Méndez'),
(86, 'Parroquia', 'Ramón Ignacio Méndez'),
(86, 'Parroquia', 'José Ignacio del Pumar'),
(87, 'Parroquia', 'Obispos'),
(87, 'Parroquia', 'Guasimitos'),
(87, 'Parroquia', 'El Real'),
(87, 'Parroquia', 'La Luz'),
(88, 'Parroquia', 'Ciudad Bolívia'),
(88, 'Parroquia', 'José Ignacio Briceño'),
(88, 'Parroquia', 'José Félix Ribas'),
(88, 'Parroquia', 'Páez'),
(89, 'Parroquia', 'Libertad'),
(89, 'Parroquia', 'Dolores'),
(89, 'Parroquia', 'Santa Rosa'),
(89, 'Parroquia', 'Palacio Fajardo'),
(90, 'Parroquia', 'Ciudad de Nutrias'),
(90, 'Parroquia', 'El Regalo'),
(90, 'Parroquia', 'Puerto Nutrias'),
(90, 'Parroquia', 'Santa Catalina'),
(91, 'Parroquia', 'Cachamay'),
(91, 'Parroquia', 'Chirica'),
(91, 'Parroquia', 'Dalla Costa'),
(91, 'Parroquia', 'Once de Abril'),
(91, 'Parroquia', 'Simón Bolívar'),
(91, 'Parroquia', 'Unare'),
(91, 'Parroquia', 'Universidad'),
(91, 'Parroquia', 'Vista al Sol'),
(91, 'Parroquia', 'Pozo Verde'),
(91, 'Parroquia', 'Yocoima'),
(91, 'Parroquia', '5 de Julio'),
(92, 'Parroquia', 'Cedeño'),
(92, 'Parroquia', 'Altagracia'),
(92, 'Parroquia', 'Ascensión Farreras'),
(92, 'Parroquia', 'Guaniamo'),
(92, 'Parroquia', 'La Urbana'),
(92, 'Parroquia', 'Pijiguaos'),
(93, 'Parroquia', 'El Callao'),
(94, 'Parroquia', 'Gran Sabana'),
(94, 'Parroquia', 'Ikabarú'),
(95, 'Parroquia', 'Catedral'),
(95, 'Parroquia', 'Zea'),
(95, 'Parroquia', 'Orinoco'),
(95, 'Parroquia', 'José Antonio Páez'),
(95, 'Parroquia', 'Marhuanta'),
(95, 'Parroquia', 'Agua Salada'),
(95, 'Parroquia', 'Vista Hermosa'),
(95, 'Parroquia', 'La Sabanita'),
(95, 'Parroquia', 'Panapana'),
(96, 'Parroquia', 'Andrés Eloy Blanco'),
(96, 'Parroquia', 'Pedro Cova'),
(97, 'Parroquia', 'Raúl Leoni'),
(97, 'Parroquia', 'Barceloneta'),
(97, 'Parroquia', 'Santa Bárbara'),
(97, 'Parroquia', 'San Francisco'),
(98, 'Parroquia', 'Roscio'),
(98, 'Parroquia', 'Salóm'),
(99, 'Parroquia', 'Sifontes'),
(99, 'Parroquia', 'Dalla Costa'),
(99, 'Parroquia', 'San Isidro'),
(100, 'Parroquia', 'Sucre'),
(100, 'Parroquia', 'Aripao'),
(100, 'Parroquia', 'Guarataro'),
(100, 'Parroquia', 'Las Majadas'),
(100, 'Parroquia', 'Moitaco'),
(101, 'Parroquia', 'Padre Pedro Chien'),
(101, 'Parroquia', 'Río Grande'),
(102, 'Parroquia', 'Bejuma'),
(102, 'Parroquia', 'Canoabo'),
(102, 'Parroquia', 'Simón Bolívar'),
(103, 'Parroquia', 'Güigüe'),
(103, 'Parroquia', 'Carabobo'),
(103, 'Parroquia', 'Tacarigua'),
(104, 'Parroquia', 'Mariara'),
(104, 'Parroquia', 'Aguas Calientes'),
(105, 'Parroquia', 'Ciudad Alianza'),
(105, 'Parroquia', 'Guacara'),
(105, 'Parroquia', 'Yagua'),
(106, 'Parroquia', 'Morón'),
(106, 'Parroquia', 'Yagua'),
(107, 'Parroquia', 'Tocuyito'),
(107, 'Parroquia', 'Independencia'),
(108, 'Parroquia', 'Los Guayos'),
(109, 'Parroquia', 'Miranda'),
(110, 'Parroquia', 'Montalbán'),
(111, 'Parroquia', 'Naguanagua'),
(112, 'Parroquia', 'Bartolomé Salóm'),
(112, 'Parroquia', 'Democracia'),
(112, 'Parroquia', 'Fraternidad'),
(112, 'Parroquia', 'Goaigoaza'),
(112, 'Parroquia', 'Juan José Flores'),
(112, 'Parroquia', 'Unión'),
(112, 'Parroquia', 'Borburata'),
(112, 'Parroquia', 'Patanemo'),
(113, 'Parroquia', 'San Diego'),
(114, 'Parroquia', 'San Joaquín'),
(115, 'Parroquia', 'Candelaria'),
(115, 'Parroquia', 'Catedral'),
(115, 'Parroquia', 'El Socorro'),
(115, 'Parroquia', 'Miguel Peña'),
(115, 'Parroquia', 'Rafael Urdaneta'),
(115, 'Parroquia', 'San Blas'),
(115, 'Parroquia', 'San José'),
(115, 'Parroquia', 'Santa Rosa'),
(115, 'Parroquia', 'Negro Primero'),
(116, 'Parroquia', 'Cojedes'),
(116, 'Parroquia', 'Juan de Mata Suárez'),
(117, 'Parroquia', 'Tinaquillo'),
(118, 'Parroquia', 'El Baúl'),
(118, 'Parroquia', 'Sucre'),
(119, 'Parroquia', 'La Aguadita'),
(119, 'Parroquia', 'Macapo'),
(120, 'Parroquia', 'El Pao'),
(121, 'Parroquia', 'El Amparo'),
(121, 'Parroquia', 'Libertad de Cojedes'),
(122, 'Parroquia', 'Rómulo Gallegos'),
(123, 'Parroquia', 'San Carlos de Austria'),
(123, 'Parroquia', 'Juan Ángel Bravo'),
(123, 'Parroquia', 'Manuel Manrique'),
(124, 'Parroquia', 'General en Jefe José Laurencio Silva'),
(125, 'Parroquia',  'Curiapo'),
(125, 'Parroquia',  'Almirante Luis Brión'),
(125, 'Parroquia',  'Francisco Aniceto Lugo'),
(125, 'Parroquia',  'Manuel Renaud'),
(125, 'Parroquia',  'Padre Barral'),
(125, 'Parroquia',  'Santos de Abelgas'),
(126, 'Parroquia',  'Imataca'),
(126, 'Parroquia',  'Cinco de Julio'),
(126, 'Parroquia',  'Juan Bautista Arismendi'),
(126, 'Parroquia',  'Manuel Piar'),
(126, 'Parroquia',  'Rómulo Gallegos'),
(127, 'Parroquia',  'Pedernales'),
(127, 'Parroquia',  'Luis Beltrán Prieto Figueroa'),
(128, 'Parroquia',  'San José (Delta Amacuro)'),
(128, 'Parroquia',  'José Vidal Marcano'),
(128, 'Parroquia',  'Juan Millán'),
(128, 'Parroquia',  'Leonardo Ruíz Pineda'),
(128, 'Parroquia',  'Mariscal Antonio José de Sucre'),
(128, 'Parroquia',  'Monseñor Argimiro García'),
(128, 'Parroquia',  'San Rafael (Delta Amacuro)'),
(128, 'Parroquia',  'Virgen del Valle'),
(35,  'Parroquia', 'Clarines'),
(35,  'Parroquia', 'Guanape'),
(35,  'Parroquia', 'Sabana de Uchire'),
(129, 'Parroquia',  'Capadare'),
(129, 'Parroquia',  'La Pastora'),
(129, 'Parroquia',  'Libertador'),
(129, 'Parroquia',  'San Juan de los Cayos'),
(130, 'Parroquia',  'Aracua'),
(130, 'Parroquia',  'La Peña'),
(130, 'Parroquia',  'San Luis'),
(131, 'Parroquia',  'Bariro'),
(131, 'Parroquia',  'Borojó'),
(131, 'Parroquia',  'Capatárida'),
(131, 'Parroquia',  'Guajiro'),
(131, 'Parroquia',  'Seque'),
(131, 'Parroquia',  'Zazárida'),
(131, 'Parroquia',  'Valle de Eroa'),
(132, 'Parroquia',  'Cacique Manaure'),
(133, 'Parroquia',  'Norte'),
(133, 'Parroquia',  'Carirubana'),
(133, 'Parroquia',  'Santa Ana'),
(133, 'Parroquia',  'Urbana Punta Cardón'),
(134, 'Parroquia',  'La Vela de Coro'),
(134, 'Parroquia',  'Acurigua'),
(134, 'Parroquia',  'Guaibacoa'),
(134, 'Parroquia',  'Las Calderas'),
(134, 'Parroquia',  'Macoruca'),
(135, 'Parroquia',  'Dabajuro'),
(136, 'Parroquia',  'Agua Clara'),
(136, 'Parroquia',  'Avaria'),
(136, 'Parroquia',  'Pedregal'),
(136, 'Parroquia',  'Piedra Grande'),
(136, 'Parroquia',  'Purureche'),
(137, 'Parroquia',  'Adaure'),
(137, 'Parroquia',  'Adícora'),
(137, 'Parroquia',  'Baraived'),
(137, 'Parroquia',  'Buena Vista'),
(137, 'Parroquia',  'Jadacaquiva'),
(137, 'Parroquia',  'El Vínculo'),
(137, 'Parroquia',  'El Hato'),
(137, 'Parroquia',  'Moruy'),
(137, 'Parroquia',  'Pueblo Nuevo'),
(138, 'Parroquia',  'Agua Larga'),
(138, 'Parroquia',  'El Paují'),
(138, 'Parroquia',  'Independencia'),
(138, 'Parroquia',  'Mapararí'),
(139, 'Parroquia',  'Agua Linda'),
(139, 'Parroquia',  'Araurima'),
(139, 'Parroquia',  'Jacura'),
(140, 'Parroquia',  'Tucacas'),
(140, 'Parroquia',  'Boca de Aroa'),
(141, 'Parroquia',  'Los Taques'),
(141, 'Parroquia',  'Judibana'),
(142, 'Parroquia',  'Mene de Mauroa'),
(142, 'Parroquia',  'San Félix'),
(142, 'Parroquia',  'Casigua'),
(143, 'Parroquia',  'Guzmán Guillermo'),
(143, 'Parroquia',  'Mitare'),
(143, 'Parroquia',  'Río Seco'),
(143, 'Parroquia',  'Sabaneta'),
(143, 'Parroquia',  'San Antonio'),
(143, 'Parroquia',  'San Gabriel'),
(143, 'Parroquia',  'Santa Ana'),
(144, 'Parroquia',  'Boca del Tocuyo'),
(144, 'Parroquia',  'Chichiriviche'),
(144, 'Parroquia',  'Tocuyo de la Costa'),
(145, 'Parroquia',  'Palmasola'),
(146, 'Parroquia',  'Cabure'),
(146, 'Parroquia',  'Colina'),
(146, 'Parroquia',  'Curimagua'),
(147, 'Parroquia',  'San José de la Costa'),
(147, 'Parroquia',  'Píritu'),
(148, 'Parroquia',  'San Francisco'),
(149, 'Parroquia',  'Sucre'),
(149, 'Parroquia',  'Pecaya'),
(150, 'Parroquia',  'Tocópero'),
(151, 'Parroquia',  'El Charal'),
(151, 'Parroquia',  'Las Vegas del Tuy'),
(151, 'Parroquia',  'Santa Cruz de Bucaral'),
(152, 'Parroquia',  'Bruzual'),
(152, 'Parroquia',  'Urumaco'),
(153, 'Parroquia',  'Puerto Cumarebo'),
(153, 'Parroquia',  'La Ciénaga'),
(153, 'Parroquia',  'La Soledad'),
(153, 'Parroquia',  'Pueblo Cumarebo'),
(153, 'Parroquia',  'Zazárida'),
(138, 'Parroquia',  'Churuguara'),
(154, 'Parroquia',  'Camaguán'),
(154, 'Parroquia',  'Puerto Miranda'),
(154, 'Parroquia',  'Uverito'),
(155, 'Parroquia',  'Chaguaramas'),
(156, 'Parroquia',  'El Socorro'),
(157, 'Parroquia',  'Tucupido'),
(157, 'Parroquia',  'San Rafael de Laya'),
(158, 'Parroquia',  'Altagracia de Orituco'),
(158, 'Parroquia',  'San Rafael de Orituco'),
(158, 'Parroquia',  'San Francisco Javier de Lezama'),
(158, 'Parroquia',  'Paso Real de Macaira'),
(158, 'Parroquia',  'Carlos Soublette'),
(158, 'Parroquia',  'San Francisco de Macaira'),
(158, 'Parroquia',  'Libertad de Orituco'),
(159, 'Parroquia',  'Cantaclaro'),
(159, 'Parroquia',  'San Juan de los Morros'),
(159, 'Parroquia',  'Parapara'),
(160, 'Parroquia',  'El Sombrero'),
(160, 'Parroquia',  'Sosa'),
(161, 'Parroquia',  'Las Mercedes'),
(161, 'Parroquia',  'Cabruta'),
(161, 'Parroquia',  'Santa Rita de Manapire'),
(162, 'Parroquia',  'Valle de la Pascua'),
(162, 'Parroquia',  'Espino'),
(163, 'Parroquia',  'San José de Unare'),
(163, 'Parroquia',  'Zaraza'),
(164, 'Parroquia',  'San José de Tiznados'),
(164, 'Parroquia',  'San Francisco de Tiznados'),
(164, 'Parroquia',  'San Lorenzo de Tiznados'),
(164, 'Parroquia',  'Ortiz'),
(165, 'Parroquia',  'Guayabal'),
(165, 'Parroquia',  'Cazorla'),
(166, 'Parroquia',  'San José de Guaribe'),
(166, 'Parroquia',  'Uveral'),
(167, 'Parroquia',  'Santa María de Ipire'),
(167, 'Parroquia',  'Altamira'),
(168, 'Parroquia',  'El Calvario'),
(168, 'Parroquia',  'El Rastro'),
(168, 'Parroquia',  'Guardatinajas'),
(168, 'Parroquia',  'Capital Urbana Calabozo'),
(169, 'Parroquia',  'Quebrada Honda de Guache'),
(169, 'Parroquia',  'Pío Tamayo'),
(169, 'Parroquia',  'Yacambú'),
(170, 'Parroquia',  'Fréitez'),
(170, 'Parroquia',  'José María Blanco'),
(171, 'Parroquia',  'Catedral'),
(171, 'Parroquia',  'Concepción'),
(171, 'Parroquia',  'El Cují'),
(171, 'Parroquia',  'Juan de Villegas'),
(171, 'Parroquia',  'Santa Rosa'),
(171, 'Parroquia',  'Tamaca'),
(171, 'Parroquia',  'Unión'),
(171, 'Parroquia',  'Aguedo Felipe Alvarado'),
(171, 'Parroquia',  'Buena Vista'),
(171, 'Parroquia',  'Juárez'),
(172, 'Parroquia',  'Juan Bautista Rodríguez'),
(172, 'Parroquia',  'Cuara'),
(172, 'Parroquia',  'Diego de Lozada'),
(172, 'Parroquia',  'Paraíso de San José'),
(172, 'Parroquia',  'San Miguel'),
(172, 'Parroquia',  'Tintorero'),
(172, 'Parroquia',  'José Bernardo Dorante'),
(172, 'Parroquia',  'Coronel Mariano Peraza '),
(173, 'Parroquia',  'Bolívar'),
(173, 'Parroquia',  'Anzoátegui'),
(173, 'Parroquia',  'Guarico'),
(173, 'Parroquia',  'Hilario Luna y Luna'),
(173, 'Parroquia',  'Humocaro Alto'),
(173, 'Parroquia',  'Humocaro Bajo'),
(173, 'Parroquia',  'La Candelaria'),
(173, 'Parroquia',  'Morán'),
(174, 'Parroquia',  'Cabudare'),
(174, 'Parroquia',  'José Gregorio Bastidas'),
(174, 'Parroquia',  'Agua Viva'),
(175, 'Parroquia',  'Sarare'),
(175, 'Parroquia',  'Buría'),
(175, 'Parroquia',  'Gustavo Vegas León'),
(176, 'Parroquia',  'Trinidad Samuel'),
(176, 'Parroquia',  'Antonio Díaz'),
(176, 'Parroquia',  'Camacaro'),
(176, 'Parroquia',  'Castañeda'),
(176, 'Parroquia',  'Cecilio Zubillaga'),
(176, 'Parroquia',  'Chiquinquirá'),
(176, 'Parroquia',  'El Blanco'),
(176, 'Parroquia',  'Espinoza de los Monteros'),
(176, 'Parroquia',  'Lara'),
(176, 'Parroquia',  'Las Mercedes'),
(176, 'Parroquia',  'Manuel Morillo'),
(176, 'Parroquia',  'Montaña Verde'),
(176, 'Parroquia',  'Montes de Oca'),
(176, 'Parroquia',  'Torres'),
(176, 'Parroquia',  'Heriberto Arroyo'),
(176, 'Parroquia',  'Reyes Vargas'),
(176, 'Parroquia',  'Altagracia'),
(177, 'Parroquia',  'Siquisique'),
(177, 'Parroquia',  'Moroturo'),
(177, 'Parroquia',  'San Miguel'),
(177, 'Parroquia',  'Xaguas'),
(204, 'Parroquia',  'Presidente Betancourt'),
(204, 'Parroquia',  'Presidente Páez'),
(204, 'Parroquia',  'Presidente Rómulo Gallegos'),
(204, 'Parroquia',  'Gabriel Picón González'),
(204, 'Parroquia',  'Héctor Amable Mora'),
(204, 'Parroquia',  'José Nucete Sardi'),
(204, 'Parroquia',  'Pulido Méndez'),
(205, 'Parroquia',  'La Azulita'),
(206, 'Parroquia',  'Santa Cruz de Mora'),
(206, 'Parroquia',  'Mesa Bolívar'),
(206, 'Parroquia',  'Mesa de Las Palmas'),
(207, 'Parroquia',  'Aricagua'),
(207, 'Parroquia',  'San Antonio'),
(208, 'Parroquia',  'Canagua'),
(208, 'Parroquia',  'Capurí'),
(208, 'Parroquia',  'Chacantá'),
(208, 'Parroquia',  'El Molino'),
(208, 'Parroquia',  'Guaimaral'),
(208, 'Parroquia',  'Mucutuy'),
(208, 'Parroquia',  'Mucuchachí'),
(209, 'Parroquia',  'Fernández Peña'),
(209, 'Parroquia',  'Matriz'),
(209, 'Parroquia',  'Montalbán'),
(209, 'Parroquia',  'Acequias'),
(209, 'Parroquia',  'Jají'),
(209, 'Parroquia',  'La Mesa'),
(209, 'Parroquia',  'San José del Sur'),
(210, 'Parroquia',  'Tucaní'),
(210, 'Parroquia',  'Florencio Ramírez'),
(211, 'Parroquia',  'Santo Domingo'),
(211, 'Parroquia',  'Las Piedras'),
(212, 'Parroquia',  'Guaraque'),
(212, 'Parroquia',  'Mesa de Quintero'),
(212, 'Parroquia',  'Río Negro'),
(213, 'Parroquia',  'Arapuey'),
(213, 'Parroquia',  'Palmira'),
(214, 'Parroquia',  'San Cristóbal de Torondoy'),
(214, 'Parroquia',  'Torondoy'),
(215, 'Parroquia',  'Antonio Spinetti Dini'),
(215, 'Parroquia',  'Arias'),
(215, 'Parroquia',  'Caracciolo Parra Pérez'),
(215, 'Parroquia',  'Domingo Peña'),
(215, 'Parroquia',  'El Llano'),
(215, 'Parroquia',  'Gonzalo Picón Febres'),
(215, 'Parroquia',  'Jacinto Plaza'),
(215, 'Parroquia',  'Juan Rodríguez Suárez'),
(215, 'Parroquia',  'Lasso de la Vega'),
(215, 'Parroquia',  'Mariano Picón Salas'),
(215, 'Parroquia',  'Milla'),
(215, 'Parroquia',  'Osuna Rodríguez'),
(215, 'Parroquia',  'Sagrario'),
(215, 'Parroquia',  'El Morro'),
(215, 'Parroquia',  'Los Nevados'),
(216, 'Parroquia',  'Andrés Eloy Blanco'),
(216, 'Parroquia',  'La Venta'),
(216, 'Parroquia',  'Piñango'),
(216, 'Parroquia',  'Timotes'),
(217, 'Parroquia',  'Eloy Paredes'),
(217, 'Parroquia',  'San Rafael de Alcázar'),
(217, 'Parroquia',  'Santa Elena de Arenales'),
(218, 'Parroquia',  'Santa María de Caparo'),
(219, 'Parroquia',  'Pueblo Llano'),
(220, 'Parroquia',  'Cacute'),
(220, 'Parroquia',  'La Toma'),
(220, 'Parroquia',  'Mucuchíes'),
(220, 'Parroquia',  'Mucurubá'),
(220, 'Parroquia',  'San Rafael'),
(221, 'Parroquia',  'Gerónimo Maldonado'),
(221, 'Parroquia',  'Bailadores'),
(222, 'Parroquia',  'Tabay'),
(223, 'Parroquia',  'Chiguará'),
(223, 'Parroquia',  'Estánquez'),
(223, 'Parroquia',  'Lagunillas'),
(223, 'Parroquia',  'La Trampa'),
(223, 'Parroquia',  'Pueblo Nuevo del Sur'),
(223, 'Parroquia',  'San Juan'),
(224, 'Parroquia',  'El Amparo'),
(224, 'Parroquia',  'El Llano'),
(224, 'Parroquia',  'San Francisco'),
(224, 'Parroquia',  'Tovar'),
(225, 'Parroquia',  'Independencia'),
(225, 'Parroquia',  'María de la Concepción Palacios Blanco'),
(225, 'Parroquia',  'Nueva Bolivia'),
(225, 'Parroquia',  'Santa Apolonia'),
(226, 'Parroquia',  'Caño El Tigre'),
(226, 'Parroquia',  'Zea'),
(248, 'Parroquia',  'Aragüita'),
(248, 'Parroquia',  'Arévalo González'),
(248, 'Parroquia',  'Capaya'),
(248, 'Parroquia',  'Caucagua'),
(248, 'Parroquia',  'Panaquire'),
(248, 'Parroquia',  'Ribas'),
(248, 'Parroquia',  'El Café'),
(248, 'Parroquia',  'Marizapa'),
(249, 'Parroquia',  'Cumbo'),
(249, 'Parroquia',  'San José de Barlovento'),
(250, 'Parroquia',  'El Cafetal'),
(250, 'Parroquia',  'Las Minas'),
(250, 'Parroquia',  'Nuestra Señora del Rosario'),
(251, 'Parroquia',  'Higuerote'),
(251, 'Parroquia',  'Curiepe'),
(251, 'Parroquia',  'Tacarigua de Brión'),
(252, 'Parroquia',  'Mamporal'),
(253, 'Parroquia',  'Carrizal'),
(254, 'Parroquia',  'Chacao'),
(255, 'Parroquia',  'Charallave'),
(255, 'Parroquia',  'Las Brisas'),
(256, 'Parroquia',  'El Hatillo'),
(257, 'Parroquia',  'Altagracia de la Montaña'),
(257, 'Parroquia',  'Cecilio Acosta'),
(257, 'Parroquia',  'Los Teques'),
(257, 'Parroquia',  'El Jarillo'),
(257, 'Parroquia',  'San Pedro'),
(257, 'Parroquia',  'Tácata'),
(257, 'Parroquia',  'Paracotos'),
(258, 'Parroquia',  'Cartanal'),
(258, 'Parroquia',  'Santa Teresa del Tuy'),
(259, 'Parroquia',  'La Democracia'),
(259, 'Parroquia',  'Ocumare del Tuy'),
(259, 'Parroquia',  'Santa Bárbara'),
(260, 'Parroquia',  'San Antonio de los Altos'),
(261, 'Parroquia',  'Río Chico'),
(261, 'Parroquia',  'El Guapo'),
(261, 'Parroquia',  'Tacarigua de la Laguna'),
(261, 'Parroquia',  'Paparo'),
(261, 'Parroquia',  'San Fernando del Guapo'),
(262, 'Parroquia',  'Santa Lucía del Tuy'),
(263, 'Parroquia',  'Cúpira'),
(263, 'Parroquia',  'Machurucuto'),
(264, 'Parroquia',  'Guarenas'),
(265, 'Parroquia',  'San Antonio de Yare'),
(265, 'Parroquia',  'San Francisco de Yare'),
(266, 'Parroquia',  'Leoncio Martínez'),
(266, 'Parroquia',  'Petare'),
(266, 'Parroquia',  'Caucagüita'),
(266, 'Parroquia',  'Filas de Mariche'),
(266, 'Parroquia',  'La Dolorita'),
(267, 'Parroquia',  'Cúa'),
(267, 'Parroquia',  'Nueva Cúa'),
(268, 'Parroquia',  'Guatire'),
(268, 'Parroquia',  'Bolívar'),
(283, 'Parroquia',  'San Antonio de Maturín'),
(283, 'Parroquia',  'San Francisco de Maturín'),
(284, 'Parroquia',  'Aguasay'),
(285, 'Parroquia',  'Caripito'),
(286, 'Parroquia',  'El Guácharo'),
(286, 'Parroquia',  'La Guanota'),
(286, 'Parroquia',  'Sabana de Piedra'),
(286, 'Parroquia',  'San Agustín'),
(286, 'Parroquia',  'Teresen'),
(286, 'Parroquia',  'Caripe'),
(287, 'Parroquia',  'Areo'),
(287, 'Parroquia',  'Capital Cedeño'),
(287, 'Parroquia',  'San Félix de Cantalicio'),
(287, 'Parroquia',  'Viento Fresco'),
(288, 'Parroquia',  'El Tejero'),
(288, 'Parroquia',  'Punta de Mata'),
(289, 'Parroquia',  'Chaguaramas'),
(289, 'Parroquia',  'Las Alhuacas'),
(289, 'Parroquia',  'Tabasca'),
(289, 'Parroquia',  'Temblador'),
(290, 'Parroquia',  'Alto de los Godos'),
(290, 'Parroquia',  'Boquerón'),
(290, 'Parroquia',  'Las Cocuizas'),
(290, 'Parroquia',  'La Cruz'),
(290, 'Parroquia',  'San Simón'),
(290, 'Parroquia',  'El Corozo'),
(290, 'Parroquia',  'El Furrial'),
(290, 'Parroquia',  'Jusepín'),
(290, 'Parroquia',  'La Pica'),
(290, 'Parroquia',  'San Vicente'),
(291, 'Parroquia',  'Aparicio'),
(291, 'Parroquia',  'Aragua de Maturín'),
(291, 'Parroquia',  'Chaguamal'),
(291, 'Parroquia',  'El Pinto'),
(291, 'Parroquia',  'Guanaguana'),
(291, 'Parroquia',  'La Toscana'),
(291, 'Parroquia',  'Taguaya'),
(292, 'Parroquia',  'Cachipo'),
(292, 'Parroquia',  'Quiriquire'),
(293, 'Parroquia',  'Santa Bárbara'),
(294, 'Parroquia',  'Barrancas'),
(294, 'Parroquia',  'Los Barrancos de Fajardo'),
(295, 'Parroquia',  'Uracoa'),
(296, 'Parroquia',  'Antolín del Campo'),
(297, 'Parroquia',  'Arismendi'),
(298, 'Parroquia',  'García'),
(298, 'Parroquia',  'Francisco Fajardo'),
(299, 'Parroquia',  'Bolívar'),
(299, 'Parroquia',  'Guevara'),
(299, 'Parroquia',  'Matasiete'),
(299, 'Parroquia',  'Santa Ana'),
(299, 'Parroquia',  'Sucre'),
(300, 'Parroquia',  'Aguirre'),
(300, 'Parroquia',  'Maneiro'),
(301, 'Parroquia',  'Adrián'),
(301, 'Parroquia',  'Juan Griego'),
(301, 'Parroquia',  'Yaguaraparo'),
(302, 'Parroquia',  'Porlamar'),
(303, 'Parroquia',  'San Francisco de Macanao'),
(303, 'Parroquia',  'Boca de Río'),
(304, 'Parroquia',  'Tubores'),
(304, 'Parroquia',  'Los Baleales'),
(305, 'Parroquia',  'Vicente Fuentes'),
(305, 'Parroquia',  'Villalba'),
(306, 'Parroquia',  'San Juan Bautista'),
(306, 'Parroquia',  'Zabala'),
(308, 'Parroquia',  'Capital Araure'),
(308, 'Parroquia',  'Río Acarigua'),
(309, 'Parroquia',  'Capital Esteller'),
(309, 'Parroquia',  'Uveral'),
(310, 'Parroquia',  'Guanare'),
(310, 'Parroquia',  'Córdoba'),
(310, 'Parroquia',  'San José de la Montaña'),
(310, 'Parroquia',  'San Juan de Guanaguanare'),
(310, 'Parroquia',  'Virgen de la Coromoto'),
(311, 'Parroquia',  'Guanarito'),
(311, 'Parroquia',  'Trinidad de la Capilla'),
(311, 'Parroquia',  'Divina Pastora'),
(312, 'Parroquia',  'Monseñor José Vicente de Unda'),
(312, 'Parroquia',  'Peña Blanca'),
(313, 'Parroquia',  'Capital Ospino'),
(313, 'Parroquia',  'Aparición'),
(313, 'Parroquia',  'La Estación'),
(314, 'Parroquia',  'Páez'),
(314, 'Parroquia',  'Payara'),
(314, 'Parroquia',  'Pimpinela'),
(314, 'Parroquia',  'Ramón Peraza'),
(315, 'Parroquia',  'Papelón'),
(315, 'Parroquia',  'Caño Delgadito'),
(316, 'Parroquia',  'San Genaro de Boconoito'),
(316, 'Parroquia',  'Antolín Tovar'),
(317, 'Parroquia',  'San Rafael de Onoto'),
(317, 'Parroquia',  'Santa Fe'),
(317, 'Parroquia',  'Thermo Morles'),
(318, 'Parroquia',  'Santa Rosalía'),
(318, 'Parroquia',  'Florida'),
(319, 'Parroquia',  'Sucre'),
(319, 'Parroquia',  'Concepción'),
(319, 'Parroquia',  'San Rafael de Palo Alzado'),
(319, 'Parroquia',  'Uvencio Antonio Velásquez'),
(319, 'Parroquia',  'San José de Saguaz'),
(319, 'Parroquia',  'Villa Rosa'),
(320, 'Parroquia',  'Turén'),
(320, 'Parroquia',  'Canelones'),
(320, 'Parroquia',  'Santa Cruz'),
(320, 'Parroquia',  'San Isidro Labrador'),
(321, 'Parroquia',  'Mariño'),
(321, 'Parroquia',  'Rómulo Gallegos'),
(322, 'Parroquia',  'San José de Aerocuar'),
(322, 'Parroquia',  'Tavera Acosta'),
(323, 'Parroquia',  'Río Caribe'),
(323, 'Parroquia',  'Antonio José de Sucre'),
(323, 'Parroquia',  'El Morro de Puerto Santo'),
(323, 'Parroquia',  'Puerto Santo'),
(323, 'Parroquia',  'San Juan de las Galdonas'),
(324, 'Parroquia',  'El Pilar'),
(324, 'Parroquia',  'El Rincón'),
(324, 'Parroquia',  'General Francisco Antonio Váquez'),
(324, 'Parroquia',  'Guaraúnos'),
(324, 'Parroquia',  'Tunapuicito'),
(324, 'Parroquia',  'Unión'),
(325, 'Parroquia',  'Santa Catalina'),
(325, 'Parroquia',  'Santa Rosa'),
(325, 'Parroquia',  'Santa Teresa'),
(325, 'Parroquia',  'Bolívar'),
(325, 'Parroquia',  'Maracapana'),
(327, 'Parroquia',  'Libertad'),
(327, 'Parroquia',  'El Paujil'),
(327, 'Parroquia',  'Yaguaraparo'),
(328, 'Parroquia',  'Cruz Salmerón Acosta'),
(328, 'Parroquia',  'Chacopata'),
(328, 'Parroquia',  'Manicuare'),
(329, 'Parroquia',  'Tunapuy'),
(329, 'Parroquia',  'Campo Elías'),
(330, 'Parroquia',  'Irapa'),
(330, 'Parroquia',  'Campo Claro'),
(330, 'Parroquia',  'Maraval'),
(330, 'Parroquia',  'San Antonio de Irapa'),
(330, 'Parroquia',  'Soro'),
(331, 'Parroquia',  'Mejía'),
(332, 'Parroquia',  'Cumanacoa'),
(332, 'Parroquia',  'Arenas'),
(332, 'Parroquia',  'Aricagua'),
(332, 'Parroquia',  'Cogollar'),
(332, 'Parroquia',  'San Fernando'),
(332, 'Parroquia',  'San Lorenzo'),
(333, 'Parroquia',  'Villa Frontado (Muelle de Cariaco)'),
(333, 'Parroquia',  'Catuaro'),
(333, 'Parroquia',  'Rendón'),
(333, 'Parroquia',  'San Cruz'),
(333, 'Parroquia',  'Santa María'),
(334, 'Parroquia',  'Altagracia'),
(334, 'Parroquia',  'Santa Inés'),
(334, 'Parroquia',  'Valentín Valiente'),
(334, 'Parroquia',  'Ayacucho'),
(334, 'Parroquia',  'San Juan'),
(334, 'Parroquia',  'Raúl Leoni'),
(334, 'Parroquia',  'Gran Mariscal'),
(335, 'Parroquia',  'Cristóbal Colón'),
(335, 'Parroquia',  'Bideau'),
(335, 'Parroquia',  'Punta de Piedras'),
(335, 'Parroquia',  'Güiria'),
(366, 'Parroquia',  'Andrés Bello'),
(367, 'Parroquia',  'Antonio Rómulo Costa'),
(368, 'Parroquia',  'Ayacucho'),
(368, 'Parroquia',  'Rivas Berti'),
(368, 'Parroquia',  'San Pedro del Río'),
(369, 'Parroquia',  'Bolívar'),
(369, 'Parroquia',  'Palotal'),
(369, 'Parroquia',  'General Juan Vicente Gómez'),
(369, 'Parroquia',  'Isaías Medina Angarita'),
(370, 'Parroquia',  'Cárdenas'),
(370, 'Parroquia',  'Amenodoro Ángel Lamus'),
(370, 'Parroquia',  'La Florida'),
(371, 'Parroquia',  'Córdoba'),
(372, 'Parroquia',  'Fernández Feo'),
(372, 'Parroquia',  'Alberto Adriani'),
(372, 'Parroquia',  'Santo Domingo'),
(373, 'Parroquia',  'Francisco de Miranda'),
(374, 'Parroquia',  'García de Hevia'),
(374, 'Parroquia',  'Boca de Grita'),
(374, 'Parroquia',  'José Antonio Páez'),
(375, 'Parroquia',  'Guásimos'),
(376, 'Parroquia',  'Independencia'),
(376, 'Parroquia',  'Juan Germán Roscio'),
(376, 'Parroquia',  'Román Cárdenas'),
(377, 'Parroquia',  'Jáuregui'),
(377, 'Parroquia',  'Emilio Constantino Guerrero'),
(377, 'Parroquia',  'Monseñor Miguel Antonio Salas'),
(378, 'Parroquia',  'José María Vargas'),
(379, 'Parroquia',  'Junín'),
(379, 'Parroquia',  'La Petrólea'),
(379, 'Parroquia',  'Quinimarí'),
(379, 'Parroquia',  'Bramón'),
(380, 'Parroquia',  'Libertad'),
(380, 'Parroquia',  'Cipriano Castro'),
(380, 'Parroquia',  'Manuel Felipe Rugeles'),
(381, 'Parroquia',  'Libertador'),
(381, 'Parroquia',  'Doradas'),
(381, 'Parroquia',  'Emeterio Ochoa'),
(381, 'Parroquia',  'San Joaquín de Navay'),
(382, 'Parroquia',  'Lobatera'),
(382, 'Parroquia',  'Constitución'),
(383, 'Parroquia',  'Michelena'),
(384, 'Parroquia',  'Panamericano'),
(384, 'Parroquia',  'La Palmita'),
(385, 'Parroquia',  'Pedro María Ureña'),
(385, 'Parroquia',  'Nueva Arcadia'),
(386, 'Parroquia',  'Delicias'),
(386, 'Parroquia',  'Pecaya'),
(387, 'Parroquia',  'Samuel Darío Maldonado'),
(387, 'Parroquia',  'Boconó'),
(387, 'Parroquia',  'Hernández'),
(388, 'Parroquia',  'La Concordia'),
(388, 'Parroquia',  'San Juan Bautista'),
(388, 'Parroquia',  'Pedro María Morantes'),
(388, 'Parroquia',  'San Sebastián'),
(388, 'Parroquia',  'Dr. Francisco Romero Lobo'),
(389, 'Parroquia',  'Seboruco'),
(390, 'Parroquia',  'Simón Rodríguez'),
(391, 'Parroquia',  'Sucre'),
(391, 'Parroquia',  'Eleazar López Contreras'),
(391, 'Parroquia',  'San Pablo'),
(392, 'Parroquia',  'Torbes'),
(393, 'Parroquia',  'Uribante'),
(393, 'Parroquia',  'Cárdenas'),
(393, 'Parroquia',  'Juan Pablo Peñalosa'),
(393, 'Parroquia',  'Potosí'),
(394, 'Parroquia',  'San Judas Tadeo'),
(395, 'Parroquia',  'Araguaney'),
(395, 'Parroquia',  'El Jaguito'),
(395, 'Parroquia',  'La Esperanza'),
(395, 'Parroquia',  'Santa Isabel'),
(396, 'Parroquia',  'Boconó'),
(396, 'Parroquia',  'El Carmen'),
(396, 'Parroquia',  'Mosquey'),
(396, 'Parroquia',  'Ayacucho'),
(396, 'Parroquia',  'Burbusay'),
(396, 'Parroquia',  'General Ribas'),
(396, 'Parroquia',  'Guaramacal'),
(396, 'Parroquia',  'Vega de Guaramacal'),
(396, 'Parroquia',  'Monseñor Jáuregui'),
(396, 'Parroquia',  'Rafael Rangel'),
(396, 'Parroquia',  'San Miguel'),
(396, 'Parroquia',  'San José'),
(397, 'Parroquia',  'Sabana Grande'),
(397, 'Parroquia',  'Cheregüé'),
(397, 'Parroquia',  'Granados'),
(398, 'Parroquia',  'Arnoldo Gabaldón'),
(398, 'Parroquia',  'Bolivia'),
(398, 'Parroquia',  'Carrillo'),
(398, 'Parroquia',  'Cegarra'),
(398, 'Parroquia',  'Chejendé'),
(398, 'Parroquia',  'Manuel Salvador Ulloa'),
(398, 'Parroquia',  'San José'),
(399, 'Parroquia',  'Carache'),
(399, 'Parroquia',  'La Concepción'),
(399, 'Parroquia',  'Cuicas'),
(399, 'Parroquia',  'Panamericana'),
(399, 'Parroquia',  'Santa Cruz'),
(400, 'Parroquia',  'Escuque'),
(400, 'Parroquia',  'La Unión'),
(400, 'Parroquia',  'Santa Rita'),
(400, 'Parroquia',  'Sabana Libre'),
(401, 'Parroquia',  'El Socorro'),
(401, 'Parroquia',  'Los Caprichos'),
(401, 'Parroquia',  'Antonio José de Sucre'),
(402, 'Parroquia',  'Campo Elías'),
(402, 'Parroquia',  'Arnoldo Gabaldón'),
(403, 'Parroquia',  'Santa Apolonia'),
(403, 'Parroquia',  'El Progreso'),
(403, 'Parroquia',  'La Ceiba'),
(403, 'Parroquia',  'Tres de Febrero'),
(404, 'Parroquia',  'El Dividive'),
(404, 'Parroquia',  'Agua Santa'),
(404, 'Parroquia',  'Agua Caliente'),
(404, 'Parroquia',  'El Cenizo'),
(404, 'Parroquia',  'Valerita'),
(405, 'Parroquia',  'Monte Carmelo'),
(405, 'Parroquia',  'Buena Vista'),
(405, 'Parroquia',  'Santa María del Horcón'),
(406, 'Parroquia',  'Motatán'),
(406, 'Parroquia',  'El Baño'),
(406, 'Parroquia',  'Jalisco'),
(407, 'Parroquia',  'Pampán'),
(407, 'Parroquia',  'Flor de Patria'),
(407, 'Parroquia',  'La Paz'),
(407, 'Parroquia',  'Santa Ana'),
(408, 'Parroquia',  'Pampanito'),
(408, 'Parroquia',  'La Concepción'),
(408, 'Parroquia',  'Pampanito II'),
(409, 'Parroquia',  'Betijoque'),
(409, 'Parroquia',  'José Gregorio Hernández'),
(409, 'Parroquia',  'La Pueblita'),
(409, 'Parroquia',  'Los Cedros'),
(410, 'Parroquia',  'Carvajal'),
(410, 'Parroquia',  'Campo Alegre'),
(410, 'Parroquia',  'Antonio Nicolás Briceño'),
(410, 'Parroquia',  'José Leonardo Suárez'),
(411, 'Parroquia',  'Sabana de Mendoza'),
(411, 'Parroquia',  'Junín'),
(411, 'Parroquia',  'Valmore Rodríguez'),
(411, 'Parroquia',  'El Paraíso'),
(412, 'Parroquia',  'Andrés Linares'),
(412, 'Parroquia',  'Chiquinquirá'),
(412, 'Parroquia',  'Cristóbal Mendoza'),
(412, 'Parroquia',  'Cruz Carrillo'),
(412, 'Parroquia',  'Matriz'),
(412, 'Parroquia',  'Monseñor Carrillo'),
(412, 'Parroquia',  'Tres Esquinas'),
(413, 'Parroquia',  'Cabimbú'),
(413, 'Parroquia',  'Jajó'),
(413, 'Parroquia',  'La Mesa de Esnujaque'),
(413, 'Parroquia',  'Santiago'),
(413, 'Parroquia',  'Tuñame'),
(413, 'Parroquia',  'La Quebrada'),
(414, 'Parroquia',  'Juan Ignacio Montilla'),
(414, 'Parroquia',  'La Beatriz'),
(414, 'Parroquia',  'La Puerta'),
(414, 'Parroquia',  'Mendoza del Valle de Momboy'),
(414, 'Parroquia',  'Mercedes Díaz'),
(414, 'Parroquia',  'San Luis'),
(415, 'Parroquia',  'Caraballeda'),
(415, 'Parroquia',  'Carayaca'),
(415, 'Parroquia',  'Carlos Soublette'),
(415, 'Parroquia',  'Caruao Chuspa'),
(415, 'Parroquia',  'Catia La Mar'),
(415, 'Parroquia',  'El Junko'),
(415, 'Parroquia',  'La Guaira'),
(415, 'Parroquia',  'Macuto'),
(415, 'Parroquia',  'Maiquetía'),
(415, 'Parroquia',  'Naiguatá'),
(415, 'Parroquia',  'Urimare'),
(416, 'Parroquia',  'Arístides Bastidas'),
(417, 'Parroquia',  'Bolívar'),
(432, 'Parroquia',  'Chivacoa'),
(432, 'Parroquia',  'Campo Elías'),
(433, 'Parroquia',  'Cocorote'),
(434, 'Parroquia',  'Independencia'),
(435, 'Parroquia',  'José Antonio Páez'),
(436, 'Parroquia',  'La Trinidad'),
(437, 'Parroquia',  'Manuel Monge'),
(438, 'Parroquia',  'Salóm'),
(438, 'Parroquia',  'Temerla'),
(438, 'Parroquia',  'Nirgua'),
(439, 'Parroquia',  'San Andrés'),
(439, 'Parroquia',  'Yaritagua'),
(440, 'Parroquia',  'San Javier'),
(440, 'Parroquia',  'Albarico'),
(440, 'Parroquia',  'San Felipe'),
(441, 'Parroquia',  'Sucre'),
(442, 'Parroquia',  'Urachiche'),
(443, 'Parroquia',  'El Guayabo'),
(443, 'Parroquia',  'Farriar'),
(466, 'Parroquia',  'Isla de Toas'),
(466, 'Parroquia',  'Monagas'),
(467, 'Parroquia',  'San Timoteo'),
(467, 'Parroquia',  'General Urdaneta'),
(467, 'Parroquia',  'Libertador'),
(467, 'Parroquia',  'Marcelino Briceño'),
(467, 'Parroquia',  'Pueblo Nuevo'),
(467, 'Parroquia',  'Manuel Guanipa Matos'),
(468, 'Parroquia',  'Ambrosio'),
(468, 'Parroquia',  'Carmen Herrera'),
(468, 'Parroquia',  'La Rosa'),
(468, 'Parroquia',  'Germán Ríos Linares'),
(468, 'Parroquia',  'San Benito'),
(468, 'Parroquia',  'Rómulo Betancourt'),
(468, 'Parroquia',  'Jorge Hernández'),
(468, 'Parroquia',  'Punta Gorda'),
(468, 'Parroquia',  'Arístides Calvani'),
(469, 'Parroquia',  'Encontrados'),
(469, 'Parroquia',  'Udón Pérez'),
(470, 'Parroquia',  'Moralito'),
(470, 'Parroquia',  'San Carlos del Zulia'),
(470, 'Parroquia',  'Santa Cruz del Zulia'),
(470, 'Parroquia',  'Santa Bárbara'),
(470, 'Parroquia',  'Urribarrí'),
(471, 'Parroquia',  'Carlos Quevedo'),
(471, 'Parroquia',  'Francisco Javier Pulgar'),
(471, 'Parroquia',  'Simón Rodríguez'),
(471, 'Parroquia',  'Guamo-Gavilanes'),
(473, 'Parroquia',  'La Concepción'),
(473, 'Parroquia',  'San José'),
(473, 'Parroquia',  'Mariano Parra León'),
(473, 'Parroquia',  'José Ramón Yépez'),
(474, 'Parroquia',  'Jesús María Semprún'),
(474, 'Parroquia',  'Barí'),
(475, 'Parroquia',  'Concepción'),
(475, 'Parroquia',  'Andrés Bello'),
(475, 'Parroquia',  'Chiquinquirá'),
(475, 'Parroquia',  'El Carmelo'),
(475, 'Parroquia',  'Potreritos'),
(476, 'Parroquia',  'Libertad'),
(476, 'Parroquia',  'Alonso de Ojeda'),
(476, 'Parroquia',  'Venezuela'),
(476, 'Parroquia',  'Eleazar López Contreras'),
(476, 'Parroquia',  'Campo Lara'),
(477, 'Parroquia',  'Bartolomé de las Casas'),
(477, 'Parroquia',  'Libertad'),
(477, 'Parroquia',  'Río Negro'),
(477, 'Parroquia',  'San José de Perijá'),
(478, 'Parroquia',  'San Rafael'),
(478, 'Parroquia',  'La Sierrita'),
(478, 'Parroquia',  'Las Parcelas'),
(478, 'Parroquia',  'Luis de Vicente'),
(478, 'Parroquia',  'Monseñor Marcos Sergio Godoy'),
(478, 'Parroquia',  'Ricaurte'),
(478, 'Parroquia',  'Tamare'),
(479, 'Parroquia',  'Antonio Borjas Romero'),
(479, 'Parroquia',  'Bolívar'),
(479, 'Parroquia',  'Cacique Mara'),
(479, 'Parroquia',  'Carracciolo Parra Pérez'),
(479, 'Parroquia',  'Cecilio Acosta'),
(479, 'Parroquia',  'Cristo de Aranza'),
(479, 'Parroquia',  'Coquivacoa'),
(479, 'Parroquia',  'Chiquinquirá'),
(479, 'Parroquia',  'Francisco Eugenio Bustamante'),
(479, 'Parroquia',  'Idelfonzo Vásquez'),
(479, 'Parroquia',  'Juana de Ávila'),
(479, 'Parroquia',  'Luis Hurtado Higuera'),
(479, 'Parroquia',  'Manuel Dagnino'),
(479, 'Parroquia',  'Olegario Villalobos'),
(479, 'Parroquia',  'Raúl Leoni'),
(479, 'Parroquia',  'Santa Lucía'),
(479, 'Parroquia',  'Venancio Pulgar'),
(479, 'Parroquia',  'San Isidro'),
(480, 'Parroquia',  'Altagracia'),
(480, 'Parroquia',  'Faría'),
(480, 'Parroquia',  'Ana María Campos'),
(480, 'Parroquia',  'San Antonio'),
(480, 'Parroquia',  'San José'),
(481, 'Parroquia',  'Donaldo García'),
(481, 'Parroquia',  'El Rosario'),
(481, 'Parroquia',  'Sixto Zambrano'),
(482, 'Parroquia',  'San Francisco'),
(482, 'Parroquia',  'El Bajo'),
(482, 'Parroquia',  'Domitila Flores'),
(482, 'Parroquia',  'Francisco Ochoa'),
(482, 'Parroquia',  'Los Cortijos'),
(482, 'Parroquia',  'Marcial Hernández'),
(483, 'Parroquia',  'Santa Rita'),
(483, 'Parroquia',  'El Mene'),
(483, 'Parroquia',  'Pedro Lucas Urribarrí'),
(483, 'Parroquia',  'José Cenobio Urribarrí'),
(484, 'Parroquia',  'Rafael Maria Baralt'),
(484, 'Parroquia',  'Manuel Manrique'),
(484, 'Parroquia',  'Rafael Urdaneta'),
(485, 'Parroquia',  'Bobures'),
(485, 'Parroquia',  'Gibraltar'),
(485, 'Parroquia',  'Heras'),
(485, 'Parroquia',  'Monseñor Arturo Álvarez'),
(485, 'Parroquia',  'Rómulo Gallegos'),
(485, 'Parroquia',  'El Batey'),
(486, 'Parroquia',  'Rafael Urdaneta'),
(486, 'Parroquia',  'La Victoria'),
(486, 'Parroquia',  'Raúl Cuenca'),
(472, 'Parroquia',  'Sinamaica'),
(472, 'Parroquia',  'Alta Guajira'),
(472, 'Parroquia',  'Elías Sánchez Rubio'),
(472, 'Parroquia',  'Guajira'),
(487, 'Parroquia',  'Altagracia'),
(487, 'Parroquia',  'Antímano'),
(487, 'Parroquia',  'Caricuao'),
(487, 'Parroquia',  'Catedral'),
(487, 'Parroquia',  'Coche'),
(487, 'Parroquia',  'El Junquito'),
(487, 'Parroquia',  'El Paraíso'),
(487, 'Parroquia',  'El Recreo'),
(487, 'Parroquia',  'El Valle'),
(487, 'Parroquia',  'La Candelaria'),
(487, 'Parroquia',  'La Pastora'),
(487, 'Parroquia',  'La Vega'),
(487, 'Parroquia',  'Macarao'),
(487, 'Parroquia',  'San Agustín'),
(487, 'Parroquia',  'San Bernardino'),
(487, 'Parroquia',  'San José'),
(487, 'Parroquia',  'San Juan'),
(487, 'Parroquia',  'San Pedro'),
(487, 'Parroquia',  'Santa Rosalía'),
(487, 'Parroquia',  'Santa Teresa'),
(487, 'Parroquia',  'Sucre (Catia)'),
(487, 'Parroquia',  '23 de enero');
 

ALTER TABLE Lugar ADD CONSTRAINT pk_lugar primary key (id);

ALTER TABLE Lugar
  ADD CONSTRAINT fk_lugar_id FOREIGN KEY (id) REFERENCES Lugar (id) ON DELETE CASCADE ON UPDATE CASCADE;